//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.SignXmlServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://singxml/", ConfigurationName="SignXmlServiceReference.SignXmlPortType")]
    public interface SignXmlPortType {
        
        // CODEGEN: Generating message contract since element name _xmlPath from namespace http://singxml/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DXPANACEASOFT.SignXmlServiceReference.signResponse sign(DXPANACEASOFT.SignXmlServiceReference.sign request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DXPANACEASOFT.SignXmlServiceReference.signResponse> signAsync(DXPANACEASOFT.SignXmlServiceReference.sign request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sign {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sign", Namespace="http://singxml/", Order=0)]
        public DXPANACEASOFT.SignXmlServiceReference.signBody Body;
        
        public sign() {
        }
        
        public sign(DXPANACEASOFT.SignXmlServiceReference.signBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://singxml/")]
    public partial class signBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _xmlPath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _xmlFileIn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _outPutPath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string _pathSignature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string _passSignature;
        
        public signBody() {
        }
        
        public signBody(string _xmlPath, string _xmlFileIn, string _outPutPath, string _pathSignature, string _passSignature) {
            this._xmlPath = _xmlPath;
            this._xmlFileIn = _xmlFileIn;
            this._outPutPath = _outPutPath;
            this._pathSignature = _pathSignature;
            this._passSignature = _passSignature;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="signResponse", Namespace="http://singxml/", Order=0)]
        public DXPANACEASOFT.SignXmlServiceReference.signResponseBody Body;
        
        public signResponse() {
        }
        
        public signResponse(DXPANACEASOFT.SignXmlServiceReference.signResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://singxml/")]
    public partial class signResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public signResponseBody() {
        }
        
        public signResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SignXmlPortTypeChannel : DXPANACEASOFT.SignXmlServiceReference.SignXmlPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignXmlPortTypeClient : System.ServiceModel.ClientBase<DXPANACEASOFT.SignXmlServiceReference.SignXmlPortType>, DXPANACEASOFT.SignXmlServiceReference.SignXmlPortType {
        
        public SignXmlPortTypeClient() {
        }
        
        public SignXmlPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignXmlPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignXmlPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignXmlPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DXPANACEASOFT.SignXmlServiceReference.signResponse DXPANACEASOFT.SignXmlServiceReference.SignXmlPortType.sign(DXPANACEASOFT.SignXmlServiceReference.sign request) {
            return base.Channel.sign(request);
        }
        
        public string sign(string _xmlPath, string _xmlFileIn, string _outPutPath, string _pathSignature, string _passSignature) {
            DXPANACEASOFT.SignXmlServiceReference.sign inValue = new DXPANACEASOFT.SignXmlServiceReference.sign();
            inValue.Body = new DXPANACEASOFT.SignXmlServiceReference.signBody();
            inValue.Body._xmlPath = _xmlPath;
            inValue.Body._xmlFileIn = _xmlFileIn;
            inValue.Body._outPutPath = _outPutPath;
            inValue.Body._pathSignature = _pathSignature;
            inValue.Body._passSignature = _passSignature;
            DXPANACEASOFT.SignXmlServiceReference.signResponse retVal = ((DXPANACEASOFT.SignXmlServiceReference.SignXmlPortType)(this)).sign(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DXPANACEASOFT.SignXmlServiceReference.signResponse> DXPANACEASOFT.SignXmlServiceReference.SignXmlPortType.signAsync(DXPANACEASOFT.SignXmlServiceReference.sign request) {
            return base.Channel.signAsync(request);
        }
        
        public System.Threading.Tasks.Task<DXPANACEASOFT.SignXmlServiceReference.signResponse> signAsync(string _xmlPath, string _xmlFileIn, string _outPutPath, string _pathSignature, string _passSignature) {
            DXPANACEASOFT.SignXmlServiceReference.sign inValue = new DXPANACEASOFT.SignXmlServiceReference.sign();
            inValue.Body = new DXPANACEASOFT.SignXmlServiceReference.signBody();
            inValue.Body._xmlPath = _xmlPath;
            inValue.Body._xmlFileIn = _xmlFileIn;
            inValue.Body._outPutPath = _outPutPath;
            inValue.Body._pathSignature = _pathSignature;
            inValue.Body._passSignature = _passSignature;
            return ((DXPANACEASOFT.SignXmlServiceReference.SignXmlPortType)(this)).signAsync(inValue);
        }
    }
}
