//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishingCustodians
    {
        public int Id { get; set; }
        public Nullable<decimal> Patrol { get; set; }
        public Nullable<decimal> SemiComplete { get; set; }
        public Nullable<decimal> TruckDriver { get; set; }
        public Nullable<decimal> ChangeHG { get; set; }
        public Nullable<decimal> CabinHR { get; set; }
        public bool State { get; set; }
        public bool Id_FishingSite { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
    }
}
