//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackgroundProcess
    {
        public int id { get; set; }
        public string code { get; set; }
        public string state { get; set; }
        public System.DateTime dateCreation { get; set; }
        public Nullable<System.DateTime> dateModification { get; set; }
    }
}
