//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIAnalisisCalidad
    {
        public string TipoAnalisis { get; set; }
        public string NumeroAnalisis { get; set; }
        public string SecuenciaTransaccional { get; set; }
        public string NumeroLote { get; set; }
        public string Certificado { get; set; }
        public string CertificadoNombre { get; set; }
        public Nullable<System.DateTime> FechaHoraLlegada { get; set; }
        public string Proveedor { get; set; }
        public string Camaronera { get; set; }
        public string NPiscina { get; set; }
        public string INP { get; set; }
        public string AMinisterial { get; set; }
        public string NTramite { get; set; }
        public string GRemision { get; set; }
        public string Producto { get; set; }
        public string TProceso { get; set; }
        public int Ngavetas { get; set; }
        public decimal Lprogramadas { get; set; }
        public decimal LRemitidas { get; set; }
        public Nullable<System.DateTime> FAnalisis { get; set; }
        public Nullable<System.TimeSpan> HAnalisis { get; set; }
        public Nullable<decimal> residuals02 { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public Nullable<decimal> Gramaje { get; set; }
        public string Referencia { get; set; }
        public string Analista { get; set; }
        public string Conforme { get; set; }
        public string Observacion { get; set; }
        public string Proceso { get; set; }
        public string Analisis { get; set; }
        public string Resultado { get; set; }
    }
}
