//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessOportunityPlanningDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessOportunityPlanningDetail()
        {
            this.ProductionLotDetail = new HashSet<ProductionLotDetail>();
            this.PurchaseRequestDetailBusinessOportunity = new HashSet<PurchaseRequestDetailBusinessOportunity>();
            this.RemissionGuideDetail = new HashSet<RemissionGuideDetail>();
            this.SalesRequestDetailBusinessOportunity = new HashSet<SalesRequestDetailBusinessOportunity>();
        }
    
        public int id { get; set; }
        public int id_businessOportunityPlanning { get; set; }
        public int id_item { get; set; }
        public decimal quantity { get; set; }
        public decimal price { get; set; }
        public int id_person { get; set; }
        public Nullable<int> id_priceList { get; set; }
        public Nullable<int> id_document { get; set; }
        public string referencePlanning { get; set; }
    
        public virtual BusinessOportunityPlaninng BusinessOportunityPlaninng { get; set; }
        public virtual Document Document { get; set; }
        public virtual Item Item { get; set; }
        public virtual Person Person { get; set; }
        public virtual PriceList PriceList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionLotDetail> ProductionLotDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRequestDetailBusinessOportunity> PurchaseRequestDetailBusinessOportunity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideDetail> RemissionGuideDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesRequestDetailBusinessOportunity> SalesRequestDetailBusinessOportunity { get; set; }
    }
}
