//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrainingTestSampling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrainingTestSampling()
        {
            this.DrainingTestDetail = new HashSet<DrainingTestDetail>();
        }
    
        public int id { get; set; }
        public decimal capacity { get; set; }
        public int idMetricUnitCapacity { get; set; }
        public int idrainingTest { get; set; }
        public int drawersNumber { get; set; }
        public decimal poundsDrained { get; set; }
        public decimal poundsAverage { get; set; }
        public decimal poundsProjected { get; set; }
    
        public virtual DrainingTest DrainingTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrainingTestDetail> DrainingTestDetail { get; set; }
    }
}
