//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryMove
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryMove()
        {
            this.AutomaticTransfer = new HashSet<AutomaticTransfer>();
            this.AutomaticTransfer1 = new HashSet<AutomaticTransfer>();
            this.InventoryMoveDetail = new HashSet<InventoryMoveDetail>();
            this.InventoryMove1 = new HashSet<InventoryMove>();
            this.InventoryMoveDetailTransfer = new HashSet<InventoryMoveDetailTransfer>();
            this.InventoryMovePlantTransfer1 = new HashSet<InventoryMovePlantTransfer>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_inventoryReason { get; set; }
        public Nullable<int> id_productionLot { get; set; }
        public Nullable<int> id_inventoryMoveToReverse { get; set; }
        public Nullable<int> idNatureMove { get; set; }
        public Nullable<int> idWarehouse { get; set; }
        public string natureSequential { get; set; }
        public Nullable<int> idInventoryPeriodDetail { get; set; }
        public Nullable<int> sequential { get; set; }
        public Nullable<bool> isAuthomatic { get; set; }
        public Nullable<int> idWarehouseEntry { get; set; }
        public Nullable<int> id_provider { get; set; }
        public Nullable<int> id_costCenter { get; set; }
        public Nullable<int> id_subCostCenter { get; set; }
        public Nullable<int> id_customer { get; set; }
        public Nullable<int> id_seller { get; set; }
        public string noFactura { get; set; }
        public string contenedor { get; set; }
        public string numberRemGuide { get; set; }
        public Nullable<decimal> totalCost { get; set; }
    
        public virtual AdvanceParametersDetail AdvanceParametersDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutomaticTransfer> AutomaticTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutomaticTransfer> AutomaticTransfer1 { get; set; }
        public virtual CostCenter CostCenter { get; set; }
        public virtual CostCenter CostCenter1 { get; set; }
        public virtual Document Document { get; set; }
        public virtual InventoryEntryMove InventoryEntryMove { get; set; }
        public virtual InventoryExitMove InventoryExitMove { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMoveDetail> InventoryMoveDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMove> InventoryMove1 { get; set; }
        public virtual InventoryMove InventoryMove2 { get; set; }
        public virtual InventoryReason InventoryReason { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Person Person2 { get; set; }
        public virtual ProductionLot ProductionLot { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMoveDetailTransfer> InventoryMoveDetailTransfer { get; set; }
        public virtual InventoryMoveExitPackingMaterial InventoryMoveExitPackingMaterial { get; set; }
        public virtual InventoryMovePlantTransfer InventoryMovePlantTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMovePlantTransfer> InventoryMovePlantTransfer1 { get; set; }
        public virtual InventoryPeriodDetail InventoryPeriodDetail { get; set; }
        public virtual InventoryTransferMove InventoryTransferMove { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
