//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemType()
        {
            this.CopackingTariffDetail = new HashSet<CopackingTariffDetail>();
            this.CostAllocationResumido = new HashSet<CostAllocationResumido>();
            this.Item = new HashSet<Item>();
            this.ItemTypeItemTypeCategory = new HashSet<ItemTypeItemTypeCategory>();
            this.ProductionCostCoefficientExecutionPlant = new HashSet<ProductionCostCoefficientExecutionPlant>();
            this.ProductionCostCoefficientExecutionWarehouse = new HashSet<ProductionCostCoefficientExecutionWarehouse>();
        }
    
        public int id { get; set; }
        public int id_inventoryLine { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int id_company { get; set; }
        public bool isActive { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CopackingTariffDetail> CopackingTariffDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostAllocationResumido> CostAllocationResumido { get; set; }
        public virtual InventoryLine InventoryLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemTypeItemTypeCategory> ItemTypeItemTypeCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionCostCoefficientExecutionPlant> ProductionCostCoefficientExecutionPlant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionCostCoefficientExecutionWarehouse> ProductionCostCoefficientExecutionWarehouse { get; set; }
        public virtual ProcessType ProcessType { get; set; }
    }
}
