//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidationCartOnCart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LiquidationCartOnCart()
        {
            this.InventoryMovePlantTransferDetail = new HashSet<InventoryMovePlantTransferDetail>();
            this.LiquidationCartOnCartDetail = new HashSet<LiquidationCartOnCartDetail>();
        }
    
        public int id { get; set; }
        public System.DateTime dateInit { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public int id_MachineForProd { get; set; }
        public int id_MachineProdOpening { get; set; }
        public int id_ProductionLot { get; set; }
        public System.TimeSpan timeInit { get; set; }
        public Nullable<System.TimeSpan> timeEnd { get; set; }
        public Nullable<int> idProccesType { get; set; }
        public Nullable<int> id_liquidator { get; set; }
        public string internalNumberDetail { get; set; }
    
        public virtual Document Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMovePlantTransferDetail> InventoryMovePlantTransferDetail { get; set; }
        public virtual MachineForProd MachineForProd { get; set; }
        public virtual MachineProdOpening MachineProdOpening { get; set; }
        public virtual Person Person { get; set; }
        public virtual ProductionLot ProductionLot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiquidationCartOnCartDetail> LiquidationCartOnCartDetail { get; set; }
    }
}
