//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricUnitConversion
    {
        public int id { get; set; }
        public int id_metricOrigin { get; set; }
        public int id_metricDestiny { get; set; }
        public decimal factor { get; set; }
        public int id_company { get; set; }
        public bool isActive { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual MetricUnit MetricUnit { get; set; }
        public virtual MetricUnit MetricUnit1 { get; set; }
    }
}
