//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleTController
    {
        public int id { get; set; }
        public int id_module { get; set; }
        public int id_tController { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual TController TController { get; set; }
    }
}
