//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningClosingPlateLyingDetail
    {
        public int id { get; set; }
        public int id_openingClosingPlateLying { get; set; }
        public int id_lot { get; set; }
        public int id_item { get; set; }
        public int id_warehouse { get; set; }
        public int id_warehouseLocation { get; set; }
        public Nullable<int> id_productionCart { get; set; }
        public decimal amount { get; set; }
        public int id_metricUnit { get; set; }
        public int id_boxedWarehouse { get; set; }
        public int id_boxedWarehouseLocation { get; set; }
        public int id_costCenter { get; set; }
        public int id_subCostCenter { get; set; }
        public Nullable<int> id_costCenterExit { get; set; }
        public Nullable<int> id_subCostCenterExit { get; set; }
    
        public virtual CostCenter CostCenter { get; set; }
        public virtual CostCenter CostCenter1 { get; set; }
        public virtual CostCenter CostCenter2 { get; set; }
        public virtual CostCenter CostCenter3 { get; set; }
        public virtual Item Item { get; set; }
        public virtual Lot Lot { get; set; }
        public virtual MetricUnit MetricUnit { get; set; }
        public virtual OpeningClosingPlateLying OpeningClosingPlateLying { get; set; }
        public virtual ProductionCart ProductionCart { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
        public virtual WarehouseLocation WarehouseLocation { get; set; }
        public virtual WarehouseLocation WarehouseLocation1 { get; set; }
    }
}
