//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PriceList()
        {
            this.AdvanceProvider = new HashSet<AdvanceProvider>();
            this.BusinessOportunityPlanningDetail = new HashSet<BusinessOportunityPlanningDetail>();
            this.CustomerPriceList = new HashSet<CustomerPriceList>();
            this.CustomerType = new HashSet<CustomerType>();
            this.PriceList1 = new HashSet<PriceList>();
            this.PriceListClassShrimp = new HashSet<PriceListClassShrimp>();
            this.PriceListClassShrimpPenalization = new HashSet<PriceListClassShrimpPenalization>();
            this.PriceListDetail = new HashSet<PriceListDetail>();
            this.PriceListDetailCategoryAdjustment = new HashSet<PriceListDetailCategoryAdjustment>();
            this.PriceListDetailFilterShow = new HashSet<PriceListDetailFilterShow>();
            this.PriceListItemSizeDetail = new HashSet<PriceListItemSizeDetail>();
            this.PriceListPersonPersonRol = new HashSet<PriceListPersonPersonRol>();
            this.PriceListProvider = new HashSet<PriceListProvider>();
            this.ProductionLot = new HashSet<ProductionLot>();
            this.PurchaseOrder = new HashSet<PurchaseOrder>();
            this.RemissionGuide = new HashSet<RemissionGuide>();
            this.SalesOrder = new HashSet<SalesOrder>();
            this.SalesQuotation = new HashSet<SalesQuotation>();
            this.SalesRequest = new HashSet<SalesRequest>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public bool isForPurchase { get; set; }
        public bool isForSold { get; set; }
        public bool isQuotation { get; set; }
        public int id_calendarPriceList { get; set; }
        public Nullable<int> id_provider { get; set; }
        public Nullable<int> id_customer { get; set; }
        public Nullable<bool> byGroup { get; set; }
        public Nullable<int> id_groupPersonByRol { get; set; }
        public Nullable<int> id_priceListBase { get; set; }
        public string list_idInventaryLineFilter { get; set; }
        public string list_idItemTypeFilter { get; set; }
        public string list_idItemGroupFilter { get; set; }
        public string list_filterShow { get; set; }
        public int id_company { get; set; }
        public Nullable<int> id_processtype { get; set; }
        public Nullable<System.DateTime> commercialDate { get; set; }
        public Nullable<int> id_UserResponsable { get; set; }
        public Nullable<int> id_certification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvanceProvider> AdvanceProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessOportunityPlanningDetail> BusinessOportunityPlanningDetail { get; set; }
        public virtual CalendarPriceList CalendarPriceList { get; set; }
        public virtual Certification Certification { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPriceList> CustomerPriceList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerType> CustomerType { get; set; }
        public virtual Document Document { get; set; }
        public virtual GroupPersonByRol GroupPersonByRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceList> PriceList1 { get; set; }
        public virtual PriceList PriceList2 { get; set; }
        public virtual ProcessType ProcessType { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceListClassShrimp> PriceListClassShrimp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceListClassShrimpPenalization> PriceListClassShrimpPenalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceListDetail> PriceListDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceListDetailCategoryAdjustment> PriceListDetailCategoryAdjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceListDetailFilterShow> PriceListDetailFilterShow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceListItemSizeDetail> PriceListItemSizeDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceListPersonPersonRol> PriceListPersonPersonRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceListProvider> PriceListProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionLot> ProductionLot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuide> RemissionGuide { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrder> SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesQuotation> SalesQuotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesRequest> SalesRequest { get; set; }
    }
}
