//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionUnitProviderTemp
    {
        public Nullable<int> nuevo { get; set; }
        public int id { get; set; }
        public int code { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string healthCertificate { get; set; }
        public bool isActive { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public Nullable<int> poolNumber { get; set; }
        public string SiteUnitProvider { get; set; }
        public Nullable<int> id_FishingSite { get; set; }
        public Nullable<int> id_shippingType { get; set; }
        public string INPnumber { get; set; }
        public string ministerialAgreement { get; set; }
        public string tramitNumber { get; set; }
        public int id_FishingZone { get; set; }
        public string poolprefix { get; set; }
        public Nullable<bool> isCopackingDetail { get; set; }
        public string poolsuffix { get; set; }
    }
}
