//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionCostBuysDistribution
    {
        public int id { get; set; }
        public int idProductionCoefficient { get; set; }
        public Nullable<int> idProcessPlant { get; set; }
        public string nameProcessPlant { get; set; }
        public Nullable<int> idInventoryLine { get; set; }
        public Nullable<int> idProcessType { get; set; }
        public decimal pounds { get; set; }
        public decimal valueCurrency { get; set; }
        public decimal percentageP { get; set; }
        public decimal coefficientP { get; set; }
    
        public virtual ProcessType ProcessType { get; set; }
        public virtual ProductionCoefficient ProductionCoefficient { get; set; }
    }
}
