//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionLotPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionLotPayment()
        {
            this.ProductionLotPaymentDistributed = new HashSet<ProductionLotPaymentDistributed>();
        }
    
        public int id { get; set; }
        public int id_productionLot { get; set; }
        public int id_item { get; set; }
        public Nullable<int> id_metricUnit { get; set; }
        public decimal quantity { get; set; }
        public Nullable<decimal> adjustMore { get; set; }
        public Nullable<decimal> adjustLess { get; set; }
        public decimal totalMU { get; set; }
        public decimal price { get; set; }
        public decimal totalToPay { get; set; }
        public decimal totalPounds { get; set; }
        public decimal fitPounds { get; set; }
        public decimal totalProcessMetricUnit { get; set; }
        public Nullable<int> id_metricUnitProcess { get; set; }
        public Nullable<decimal> quantityEntered { get; set; }
        public Nullable<decimal> quantityPoundsClose { get; set; }
        public Nullable<decimal> totalKgs { get; set; }
        public Nullable<decimal> totalLbs { get; set; }
        public Nullable<decimal> totalPriceDis { get; set; }
        public Nullable<decimal> priceDis { get; set; }
        public Nullable<decimal> differencia { get; set; }
        public Nullable<bool> distributedd { get; set; }
        public Nullable<decimal> precioDisF { get; set; }
        public Nullable<decimal> rendimientoF { get; set; }
        public Nullable<decimal> priceEdition { get; set; }
        public decimal totalProcessMetricUnitEq { get; set; }
        public decimal totalToPayEq { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual MetricUnit MetricUnit { get; set; }
        public virtual MetricUnit MetricUnit1 { get; set; }
        public virtual ProductionLot ProductionLot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionLotPaymentDistributed> ProductionLotPaymentDistributed { get; set; }
    }
}
