//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class remissionGuideResp
    {
        public int id { get; set; }
        public int id_reciver { get; set; }
        public int id_reason { get; set; }
        public string route { get; set; }
        public string startAdress { get; set; }
        public System.DateTime despachureDate { get; set; }
        public System.DateTime arrivalDate { get; set; }
        public System.DateTime returnDate { get; set; }
        public string uniqueCustomDocument { get; set; }
        public bool isExport { get; set; }
        public Nullable<int> id_providerRemisionGuide { get; set; }
        public Nullable<int> id_priceList { get; set; }
        public Nullable<int> id_buyer { get; set; }
        public Nullable<int> id_protectiveProvider { get; set; }
        public Nullable<int> id_productionUnitProvider { get; set; }
        public Nullable<int> id_productionUnitProviderPool { get; set; }
        public string descriptionpurchaseorder { get; set; }
        public Nullable<bool> isInternal { get; set; }
        public Nullable<int> id_RemisionGuideReassignment { get; set; }
        public Nullable<int> id_shippingType { get; set; }
        public Nullable<bool> hasEntrancePlanctProduction { get; set; }
        public Nullable<bool> hasExitPlanctProduction { get; set; }
        public Nullable<System.TimeSpan> despachurehour { get; set; }
        public Nullable<int> id_TransportTariffType { get; set; }
        public Nullable<int> id_tbsysCatalogState { get; set; }
        public Nullable<System.DateTime> despachureHourDt { get; set; }
        public int id_RemissionGuideType { get; set; }
        public Nullable<int> id_personProcessPlant { get; set; }
        public Nullable<bool> isCopackingRG { get; set; }
    }
}
