//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemissionGuideCustomizedIceBuyInformation
    {
        public int id_RemissionGuide { get; set; }
        public int id_BuyIce { get; set; }
        public int quantityIceBagsRequested { get; set; }
        public Nullable<int> id_ProviderIceBags { get; set; }
        public string name_ProviderIceBags { get; set; }
        public string descriptionInfo { get; set; }
        public Nullable<System.DateTime> dateApproved { get; set; }
        public Nullable<int> id_UserApproved { get; set; }
        public bool isActive { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual RemissionGuide RemissionGuide { get; set; }
    }
}
