//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinoListaProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestInventoryMove
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestInventoryMove()
        {
            this.RequestInventoryMoveDetail = new HashSet<RequestInventoryMoveDetail>();
            this.RequestInventoryMoveTotals = new HashSet<RequestInventoryMoveTotals>();
        }
    
        public int id { get; set; }
        public int id_PersonRequest { get; set; }
        public Nullable<int> id_Warehouse { get; set; }
        public Nullable<int> id_Provider { get; set; }
        public Nullable<int> id_Customer { get; set; }
        public int id_NatureMove { get; set; }
    
        public virtual AdvanceParametersDetail AdvanceParametersDetail { get; set; }
        public virtual Document Document { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Person Person2 { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestInventoryMoveDetail> RequestInventoryMoveDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestInventoryMoveTotals> RequestInventoryMoveTotals { get; set; }
    }
}
