//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCategoryTypeBusiness
    {
        public int id { get; set; }
        public int id_clientCategory { get; set; }
        public int id_customerType { get; set; }
        public int id_businessLine { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
    
        public virtual BusinessLine BusinessLine { get; set; }
        public virtual ClientCategory ClientCategory { get; set; }
        public virtual CustomerType CustomerType { get; set; }
    }
}
