//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCreditInfo
    {
        public int id_customer { get; set; }
        public int creditDays { get; set; }
        public decimal creditQuota { get; set; }
        public decimal discountRate { get; set; }
        public Nullable<int> id_paymentMethodCusm { get; set; }
        public string name_paymentMethod { get; set; }
        public Nullable<int> id_paymentTerm { get; set; }
        public string name_paymentTerm { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual PaymentTerm PaymentTerm { get; set; }
    }
}
