//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrameworkContractExtension
    {
        public int id { get; set; }
        public int id_frameworkContract { get; set; }
        public int id_frameworkContractItem { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<decimal> amout { get; set; }
        public Nullable<bool> isSave { get; set; }
    
        public virtual FrameworkContract FrameworkContract { get; set; }
        public virtual FrameworkContractItem FrameworkContractItem { get; set; }
    }
}
