//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidationFreight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LiquidationFreight()
        {
            this.LiquidationFreightDetail = new HashSet<LiquidationFreightDetail>();
        }
    
        public int id { get; set; }
        public int id_providertransport { get; set; }
        public Nullable<decimal> pricedays { get; set; }
        public Nullable<decimal> priceextension { get; set; }
        public Nullable<decimal> priceadjustment { get; set; }
        public Nullable<decimal> pricetotal { get; set; }
        public Nullable<decimal> pricesubtotal { get; set; }
        public Nullable<decimal> priceavance { get; set; }
        public decimal price { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Provider Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiquidationFreightDetail> LiquidationFreightDetail { get; set; }
    }
}
