//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionLotDispatchMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionLotDispatchMaterial()
        {
            this.InventoryMoveDetailEntryDispatchMaterialsInProductionLot = new HashSet<InventoryMoveDetailEntryDispatchMaterialsInProductionLot>();
            this.ProductionLotDispatchMaterialRemissionDetail = new HashSet<ProductionLotDispatchMaterialRemissionDetail>();
        }
    
        public int id { get; set; }
        public int id_productionLot { get; set; }
        public int id_item { get; set; }
        public Nullable<int> id_warehouse { get; set; }
        public Nullable<int> id_warehouseLocation { get; set; }
        public decimal sourceExitQuantity { get; set; }
        public decimal sendedDestinationQuantity { get; set; }
        public decimal arrivalDestinationQuantity { get; set; }
        public decimal arrivalGoodCondition { get; set; }
        public decimal arrivalBadCondition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMoveDetailEntryDispatchMaterialsInProductionLot> InventoryMoveDetailEntryDispatchMaterialsInProductionLot { get; set; }
        public virtual Item Item { get; set; }
        public virtual ProductionLot ProductionLot { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual WarehouseLocation WarehouseLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionLotDispatchMaterialRemissionDetail> ProductionLotDispatchMaterialRemissionDetail { get; set; }
    }
}
