//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionScheduleScheduleDetailPurchaseRequestDetail
    {
        public int id { get; set; }
        public Nullable<int> id_productionScheduleScheduleDetail { get; set; }
        public int id_productionSchedule { get; set; }
        public int id_purchaseRequestDetail { get; set; }
        public decimal quantity { get; set; }
    
        public virtual ProductionSchedule ProductionSchedule { get; set; }
        public virtual ProductionScheduleScheduleDetail ProductionScheduleScheduleDetail { get; set; }
        public virtual PurchaseRequestDetail PurchaseRequestDetail { get; set; }
    }
}
