//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionLotDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionLotDetail()
        {
            this.InventoryMoveDetailEntryProductionLotDetail = new HashSet<InventoryMoveDetailEntryProductionLotDetail>();
            this.InventoryMoveDetailExitProductionLotDetail = new HashSet<InventoryMoveDetailExitProductionLotDetail>();
            this.ProductionLotDetailPurchaseDetail = new HashSet<ProductionLotDetailPurchaseDetail>();
            this.ProductionLotDetailQualityControl = new HashSet<ProductionLotDetailQualityControl>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_productionLot { get; set; }
        public int id_item { get; set; }
        public Nullable<int> id_originLot { get; set; }
        public int id_warehouse { get; set; }
        public int id_warehouseLocation { get; set; }
        public decimal quantityOrdered { get; set; }
        public decimal quantityRemitted { get; set; }
        public decimal quantityRecived { get; set; }
        public Nullable<decimal> quantityProcessed { get; set; }
        public Nullable<int> id_businessOportunityPlanningDetail { get; set; }
        public Nullable<decimal> quantitydrained { get; set; }
    
        public virtual BusinessOportunityPlanningDetail BusinessOportunityPlanningDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMoveDetailEntryProductionLotDetail> InventoryMoveDetailEntryProductionLotDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMoveDetailExitProductionLotDetail> InventoryMoveDetailExitProductionLotDetail { get; set; }
        public virtual Item Item { get; set; }
        public virtual ProductionLot ProductionLot { get; set; }
        public virtual ProductionLot ProductionLot1 { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual WarehouseLocation WarehouseLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionLotDetailPurchaseDetail> ProductionLotDetailPurchaseDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionLotDetailQualityControl> ProductionLotDetailQualityControl { get; set; }
    }
}
