//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderDetail()
        {
            this.InventoryMoveDetailPurchaseOrder = new HashSet<InventoryMoveDetailPurchaseOrder>();
            this.ProductionLotDetailPurchaseDetail = new HashSet<ProductionLotDetailPurchaseDetail>();
            this.PurchaseOrderDetailPurchaseRequest = new HashSet<PurchaseOrderDetailPurchaseRequest>();
            this.RemissionGuideDetailPurchaseOrderDetail = new HashSet<RemissionGuideDetailPurchaseOrderDetail>();
        }
    
        public int id { get; set; }
        public int id_item { get; set; }
        public int id_purchaseOrder { get; set; }
        public decimal quantityRequested { get; set; }
        public decimal quantityOrdered { get; set; }
        public decimal quantityApproved { get; set; }
        public decimal quantityReceived { get; set; }
        public decimal quantityDispatched { get; set; }
        public decimal price { get; set; }
        public decimal iva { get; set; }
        public decimal subtotal { get; set; }
        public decimal total { get; set; }
        public bool isActive { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public Nullable<int> id_Grammage { get; set; }
        public string productionUnitProviderPoolreference { get; set; }
    
        public virtual Grammage Grammage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMoveDetailPurchaseOrder> InventoryMoveDetailPurchaseOrder { get; set; }
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionLotDetailPurchaseDetail> ProductionLotDetailPurchaseDetail { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetailPurchaseRequest> PurchaseOrderDetailPurchaseRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideDetailPurchaseOrderDetail> RemissionGuideDetailPurchaseOrderDetail { get; set; }
    }
}
