//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityControlConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QualityControlConfiguration()
        {
            this.QualityControl = new HashSet<QualityControl>();
            this.QualityControlConfigurationAnalysisDataTypeValidate = new HashSet<QualityControlConfigurationAnalysisDataTypeValidate>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public int sequential { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public bool isSystem { get; set; }
        public int id_company { get; set; }
        public bool isActive { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityControl> QualityControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityControlConfigurationAnalysisDataTypeValidate> QualityControlConfigurationAnalysisDataTypeValidate { get; set; }
        public virtual QualityControlConfigurationConformity QualityControlConfigurationConformity { get; set; }
    }
}
