//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityControl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QualityControl()
        {
            this.AdvanceProviderRemissionGuide = new HashSet<AdvanceProviderRemissionGuide>();
            this.ProductionLotDetailQualityControl = new HashSet<ProductionLotDetailQualityControl>();
            this.QualityControlDetail = new HashSet<QualityControlDetail>();
        }
    
        public int id { get; set; }
        public string number { get; set; }
        public int id_qualityControlConfiguration { get; set; }
        public Nullable<int> id_warehouse { get; set; }
        public Nullable<int> id_warehouseLocation { get; set; }
        public Nullable<int> id_item { get; set; }
        public Nullable<int> id_lot { get; set; }
        public int id_analyst { get; set; }
        public string reference { get; set; }
        public string description { get; set; }
        public int id_company { get; set; }
        public bool isConforms { get; set; }
        public Nullable<bool> isConformityOnHeader { get; set; }
        public Nullable<System.DateTime> qualityControlDate { get; set; }
        public Nullable<System.TimeSpan> qualityControlTime { get; set; }
        public Nullable<decimal> temperature { get; set; }
        public Nullable<decimal> residual { get; set; }
        public int id_processType { get; set; }
        public Nullable<decimal> wholePerformance { get; set; }
        public Nullable<decimal> grammageReference { get; set; }
        public Nullable<decimal> QuantityPoundsReceived { get; set; }
        public Nullable<int> DrawersReceived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvanceProviderRemissionGuide> AdvanceProviderRemissionGuide { get; set; }
        public virtual Document Document { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Item Item { get; set; }
        public virtual Lot Lot { get; set; }
        public virtual ProcessType ProcessType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionLotDetailQualityControl> ProductionLotDetailQualityControl { get; set; }
        public virtual QualityControlConfiguration QualityControlConfiguration { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual WarehouseLocation WarehouseLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityControlDetail> QualityControlDetail { get; set; }
        public virtual QualityControlResultConformityOnHeaderValue QualityControlResultConformityOnHeaderValue { get; set; }
    }
}
