//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemissionGuide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RemissionGuide()
        {
            this.Invoice = new HashSet<Invoice>();
            this.LiquidationFreightDetail = new HashSet<LiquidationFreightDetail>();
            this.ProductionLotOrigin = new HashSet<ProductionLotOrigin>();
            this.RemissionGuideDispatchMaterial = new HashSet<RemissionGuideDispatchMaterial>();
            this.RemissionGuideSecuritySeal = new HashSet<RemissionGuideSecuritySeal>();
            this.RemissionGuideDetail = new HashSet<RemissionGuideDetail>();
            this.RemissionGuide1 = new HashSet<RemissionGuide>();
            this.RemissionGuideAssignedStaff = new HashSet<RemissionGuideAssignedStaff>();
            this.RemissionGuideRiverDetail = new HashSet<RemissionGuideRiverDetail>();
        }
    
        public int id { get; set; }
        public int id_reciver { get; set; }
        public int id_reason { get; set; }
        public string route { get; set; }
        public string startAdress { get; set; }
        public System.DateTime despachureDate { get; set; }
        public System.DateTime arrivalDate { get; set; }
        public System.DateTime returnDate { get; set; }
        public string uniqueCustomDocument { get; set; }
        public bool isExport { get; set; }
        public Nullable<int> id_providerRemisionGuide { get; set; }
        public Nullable<int> id_priceList { get; set; }
        public Nullable<int> id_buyer { get; set; }
        public Nullable<int> id_protectiveProvider { get; set; }
        public Nullable<int> id_productionUnitProvider { get; set; }
        public Nullable<int> id_productionUnitProviderPool { get; set; }
        public string descriptionpurchaseorder { get; set; }
        public Nullable<bool> isInternal { get; set; }
        public Nullable<int> id_RemisionGuideReassignment { get; set; }
        public Nullable<int> id_shippingType { get; set; }
        public Nullable<bool> hasEntrancePlanctProduction { get; set; }
        public Nullable<bool> hasExitPlanctProduction { get; set; }
        public Nullable<System.TimeSpan> despachurehour { get; set; }
        public Nullable<int> id_TransportTariffType { get; set; }
        public Nullable<int> id_tbsysCatalogState { get; set; }
    
        public virtual Document Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiquidationFreightDetail> LiquidationFreightDetail { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual PriceList PriceList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionLotOrigin> ProductionLotOrigin { get; set; }
        public virtual ProductionUnitProvider ProductionUnitProvider { get; set; }
        public virtual ProductionUnitProviderPool ProductionUnitProviderPool { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual PurchaseOrderShippingType PurchaseOrderShippingType { get; set; }
        public virtual RemGuideLiqTransportation RemGuideLiqTransportation { get; set; }
        public virtual RemissionGuideReason RemissionGuideReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideDispatchMaterial> RemissionGuideDispatchMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideSecuritySeal> RemissionGuideSecuritySeal { get; set; }
        public virtual RemissionGuideTransportation RemissionGuideTransportation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideDetail> RemissionGuideDetail { get; set; }
        public virtual TransportTariffType TransportTariffType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuide> RemissionGuide1 { get; set; }
        public virtual RemissionGuide RemissionGuide2 { get; set; }
        public virtual tbsysCatalogState tbsysCatalogState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideAssignedStaff> RemissionGuideAssignedStaff { get; set; }
        public virtual RemissionGuideControlVehicle RemissionGuideControlVehicle { get; set; }
        public virtual RemissionGuideExportInformation RemissionGuideExportInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideRiverDetail> RemissionGuideRiverDetail { get; set; }
    }
}
