//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderDetailSalesRequest
    {
        public int id { get; set; }
        public int id_salesOrderDetail { get; set; }
        public int id_salesRequest { get; set; }
        public Nullable<int> id_salesRequestDetail { get; set; }
        public decimal quantity { get; set; }
    
        public virtual SalesOrderDetail SalesOrderDetail { get; set; }
        public virtual SalesRequest SalesRequest { get; set; }
        public virtual SalesRequestDetail SalesRequestDetail { get; set; }
    }
}
