//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAcNivelOrganico2
    {
        public string CCiNivelOrganico1 { get; set; }
        public string CCiNivelOrganico2 { get; set; }
        public string CDsNivelOrganico2 { get; set; }
        public string CCeNivelOrganico2 { get; set; }
    }
}
