//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAIDetTipoReporte
    {
        public string CCiTipoReporte { get; set; }
        public int NNuSecReporte { get; set; }
        public string CDsTituloReporte { get; set; }
        public string CSnReimpresion { get; set; }
    }
}
