//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAcActivoFijo
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CCiActivo { get; set; }
        public string CDsActivo { get; set; }
        public string CCeActivo { get; set; }
        public string CSNRevalorizado { get; set; }
        public string CSNRevalorizadoSistema { get; set; }
        public System.DateTime DFiFecCompra { get; set; }
        public decimal NNuValorActivo { get; set; }
        public decimal NNuCantidad { get; set; }
        public string CCiContacto { get; set; }
        public string CTxSerie { get; set; }
        public string CTxUbicacion { get; set; }
        public string CCiResponsable { get; set; }
        public string CCtDepreciacionNEC { get; set; }
        public decimal NNuDeprecAcumuladaNEC { get; set; }
        public decimal NNuPorcDeprNEC { get; set; }
        public decimal NNuDeprecMensualNEC { get; set; }
        public short NNuAnioVidaNEC { get; set; }
        public short NNuMesesDepreciadosNEC { get; set; }
        public System.DateTime DFiDepreciacionNEC { get; set; }
        public System.DateTime DFfDepreciacionNEC { get; set; }
        public decimal NNuValorResidualNEC { get; set; }
        public string CCtDepreciacionNIIF { get; set; }
        public decimal NNuValorActivoNIIF { get; set; }
        public decimal NNuDeprecAcumuladaNIIF { get; set; }
        public decimal NNuDeprecMensualNIIF { get; set; }
        public short NNuAnioVidaNIIF { get; set; }
        public short NNuMesesVidaNIIF { get; set; }
        public short NNuMesesDepreciadosNIIF { get; set; }
        public System.DateTime DFiDepreciacionNIIF { get; set; }
        public System.DateTime DFfDepreciacionNIIF { get; set; }
        public decimal NNuValorResidualNIIF { get; set; }
        public decimal NNuValorActivoRev { get; set; }
        public short NNuMesesVidaUtilRev { get; set; }
        public decimal NNuDeprecAcumuladaRev { get; set; }
        public decimal NNuDeprecMensualRev { get; set; }
        public short NNuMesesDepreciadosRev { get; set; }
        public System.DateTime DFiDepreciacionRev { get; set; }
        public System.DateTime DFfDepreciacionRev { get; set; }
        public decimal NNuValorResidualRev { get; set; }
        public string CCiPrototipoDeprec { get; set; }
        public string CCiTipoAuxiliar { get; set; }
        public string CCiAuxiliar { get; set; }
        public string CCiDpto { get; set; }
        public string CCiProyecto { get; set; }
        public string CCiSubProyecto { get; set; }
        public string CDsOrigen { get; set; }
        public int NnuFacturaRefe { get; set; }
        public string CDsModelo { get; set; }
        public string CDsParte { get; set; }
        public int NnuOrdenCompra { get; set; }
        public int NnuSecuOrdenCompra { get; set; }
        public string CCiAlterno { get; set; }
        public string CCiCodigoBarra { get; set; }
        public string CCiCodigoBarraPadre { get; set; }
        public string CCiCodigoAnterior { get; set; }
        public string CCiCodigoMantenimiento { get; set; }
        public string CCiEstado { get; set; }
        public string CCiNivelFamilia1 { get; set; }
        public string CCiNivelFamilia2 { get; set; }
        public string CCiNivelFamilia3 { get; set; }
        public string CDsDescripcionLarga { get; set; }
        public string CCiNivelGeografico1 { get; set; }
        public string CCiNivelGeografico2 { get; set; }
        public string CCiNivelGeografico3 { get; set; }
        public string CCiNivelOrganico1 { get; set; }
        public string CCiNivelOrganico2 { get; set; }
        public string CCiNivelOrganico3 { get; set; }
        public string CDsObservacionAdicional { get; set; }
        public string CDsCaracteristica1 { get; set; }
        public string CDsCaracteristica2 { get; set; }
        public string CDsCaracteristica3 { get; set; }
        public string CDsCaracteristica4 { get; set; }
        public string CDsCaracteristica5 { get; set; }
        public string CDsCaracteristica6 { get; set; }
        public string CDsCaracteristica7 { get; set; }
        public string CDsCaracteristica8 { get; set; }
        public string CDsCaracteristica9 { get; set; }
        public string CDsCaracteristica10 { get; set; }
        public string CCiOrigen { get; set; }
        public short NNuNivelActivo { get; set; }
        public System.DateTime DFiIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFmModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
    }
}
