//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAPCxpCabRetencion
    {
        public int NIdAPCxpRetencion { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public int NNuAnio { get; set; }
        public int NNuPeriodo { get; set; }
        public System.DateTime DFxRetencion { get; set; }
        public string CNuSerie { get; set; }
        public int NNuRetencion { get; set; }
        public string CNuAutorizacion { get; set; }
        public System.DateTime DFxEmision { get; set; }
        public string CCiProveedor { get; set; }
        public string CCiUsuarioRetencion { get; set; }
        public string CCiCampoAdicional1 { get; set; }
        public string CNoCampoAdicional1 { get; set; }
        public string CCiCampoAdicional2 { get; set; }
        public string CNoCampoAdicional2 { get; set; }
        public string CCiCampoAdicional3 { get; set; }
        public string CNoCampoAdicional3 { get; set; }
        public string CCiCampoAdicional4 { get; set; }
        public string CNoCampoAdicional4 { get; set; }
        public string CCiCampoAdicional5 { get; set; }
        public string CNoCampoAdicional5 { get; set; }
        public string CCiCampoAdicional6 { get; set; }
        public string CNoCampoAdicional6 { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CCiEstacionIngreso { get; set; }
        public System.DateTime DFiIngreso { get; set; }
    }
}
