//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAPCxpDetRetencionXml
    {
        public int NIdAPCxpRetencionXml { get; set; }
        public int NNuSecuencia { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> baseImponible { get; set; }
        public Nullable<decimal> porcentajeRetener { get; set; }
        public Nullable<decimal> valorRetenido { get; set; }
        public string codDocSustento { get; set; }
        public string numDocSustento { get; set; }
    }
}
