//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBcFormatoTransfBco
    {
        public string CCiSistemaTransf { get; set; }
        public string CCiFormatoTransfBco { get; set; }
        public string CNoFormatoTransfBco { get; set; }
        public string CCeFormatoTransfBco { get; set; }
    }
}
