//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCiContactos
    {
        public string CCiAuxiliar { get; set; }
        public string CCiIdentificacion { get; set; }
        public string CCtIdentificacion { get; set; }
        public string CTxRazon { get; set; }
        public string CNuFax { get; set; }
        public string CTxEmail { get; set; }
        public string CNuTelefono1 { get; set; }
        public string CNuTelefono2 { get; set; }
        public string CNoPersonaContac { get; set; }
        public string CTxCalle { get; set; }
        public string CTxNumeroDomic { get; set; }
        public string CTxCiudad { get; set; }
        public string CCiProvincia { get; set; }
        public string CTxPais { get; set; }
        public string CSnContriEspecial { get; set; }
        public Nullable<int> CNuDiasCreditos { get; set; }
        public string CCtOrigen { get; set; }
        public string CCeContacto { get; set; }
        public string CNuCedula1 { get; set; }
        public string CTxNombre1 { get; set; }
        public string CtxDireccion1 { get; set; }
        public string CTxTelefono1 { get; set; }
        public string CNuCedula2 { get; set; }
        public string CTxNombre2 { get; set; }
        public string CtxDireccion2 { get; set; }
        public string CTxTelefono2 { get; set; }
        public string CNuCedula3 { get; set; }
        public string CTxNombre3 { get; set; }
        public string CtxDireccion3 { get; set; }
        public string CTxTelefono3 { get; set; }
    }
}
