//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCpRelAnticipoOrdenPago
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CCiTipoMvto { get; set; }
        public int NNuAnioMvtoBco { get; set; }
        public int NNuSecMvtoBco { get; set; }
        public int NNuCicloMvtoBco { get; set; }
        public int NNuSecCicloDcto { get; set; }
        public int NNuSecuencia { get; set; }
        public int NNuOrdenPago { get; set; }
        public decimal NNuAplicado { get; set; }
        public string CCeAplicacion { get; set; }
        public System.DateTime DFxIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CCiEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFxAnula { get; set; }
        public string CCiUsuarioAnula { get; set; }
        public string CDsEstacionAnula { get; set; }
    }
}
