//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCbSerieReciberoExt
    {
        public string CCiCompania { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CNuSerieRecibero { get; set; }
        public decimal NNuSecuencia { get; set; }
        public string CNuSerie { get; set; }
        public string CNuAutorizacion { get; set; }
        public decimal NNuDctoIni { get; set; }
        public decimal NNuDctoFin { get; set; }
        public decimal NNuDcto { get; set; }
        public string CCeSerie { get; set; }
    }
}
