//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCiDetMvtosBcosDevAnticipo
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CCiTipoMvto { get; set; }
        public decimal NNuSecuencia { get; set; }
        public decimal NNuAnio { get; set; }
        public decimal NNuRegistro { get; set; }
        public Nullable<int> NNuPago { get; set; }
        public Nullable<decimal> NNuValor { get; set; }
        public string CCiTipoMvtoBcoAntc { get; set; }
        public Nullable<int> NNuAnioMvtoBcoAntc { get; set; }
        public string CCeDevAnticipo { get; set; }
        public Nullable<int> NNuSecDetAnticipo { get; set; }
        public string CCtAnticipo { get; set; }
    }
}
