//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCiDetMvtosBcos
    {
        public string CciCia { get; set; }
        public string CciDivision { get; set; }
        public string CciSucursal { get; set; }
        public string CCiTipoMvto { get; set; }
        public decimal NNuSecuencia { get; set; }
        public decimal NNuAnio { get; set; }
        public decimal NNuRegistro { get; set; }
        public string CCiCuenta { get; set; }
        public string CCiTipoAuxiliar { get; set; }
        public string CCiAuxiliar { get; set; }
        public string CCiDpto { get; set; }
        public string CCiProyecto { get; set; }
        public string CCiSubProyecto { get; set; }
        public Nullable<decimal> NNuDebito { get; set; }
        public Nullable<decimal> NNuCredito { get; set; }
        public string CDsDetalle { get; set; }
        public string CTxReservadoUsuario { get; set; }
        public decimal NNuRegistroComp { get; set; }
        public string CCiTipoDocCta { get; set; }
        public Nullable<long> NnuNroDocCta { get; set; }
        public Nullable<System.DateTime> DFmFechaDocCta { get; set; }
        public string CCiTipoDocAux { get; set; }
        public Nullable<decimal> NnuNroDocAux { get; set; }
        public Nullable<System.DateTime> DFcAuxiliar { get; set; }
        public Nullable<System.DateTime> DfcFechaVenc { get; set; }
        public string CDsReferencia01 { get; set; }
        public string CSnMostrar { get; set; }
    }
}
