//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCpPagos
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public decimal NNuPago { get; set; }
        public string CCiCiaOrden { get; set; }
        public string CCiDivisionOrden { get; set; }
        public string CCiSucursalOrden { get; set; }
        public decimal NNuOrdenPago { get; set; }
        public System.DateTime DFcPago { get; set; }
        public string NNucheque { get; set; }
        public decimal NNuValor { get; set; }
        public System.DateTime DFiFechaIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CCePago { get; set; }
        public Nullable<System.DateTime> FFxContabiliza { get; set; }
        public string CtxInterComp { get; set; }
        public string CCiTipoMvtoBanc { get; set; }
        public Nullable<decimal> NNuSecuenciaMvtoBanc { get; set; }
        public Nullable<decimal> NNuAnio { get; set; }
        public string CCiPrototipo { get; set; }
        public string CCiBanco { get; set; }
        public string CCiCtaCte { get; set; }
        public string CCtCaja { get; set; }
        public string CCiCajaBanco { get; set; }
        public string CCiCajaCtaCte { get; set; }
        public string CCeFormaPago { get; set; }
        public string CCtTipoOrden { get; set; }
        public string CCiAuxiliar { get; set; }
        public string CDsBeneficiario { get; set; }
        public string CDsDetalle { get; set; }
        public string CDsReferencia { get; set; }
        public string CSNAnticipo { get; set; }
        public string CCeAnticipo { get; set; }
        public Nullable<short> NNuAnioMvtoBancAnul { get; set; }
        public string CCiTipoMvtoBancAnul { get; set; }
        public Nullable<int> NNuSecuenciaMvtoBancAnul { get; set; }
        public string CCiMotivo { get; set; }
        public string CCiEstadoCheque { get; set; }
        public Nullable<System.DateTime> DFxModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public string CSNPreaviso { get; set; }
        public string CCiProveedor { get; set; }
        public string CctCheque { get; set; }
        public Nullable<int> NNuControlComprobante { get; set; }
        public Nullable<int> NNuControlInterCia { get; set; }
        public Nullable<int> NNuControlAnula { get; set; }
        public string CctChequeAnterior { get; set; }
        public Nullable<int> NNuControlAnulaInterCia { get; set; }
        public Nullable<System.DateTime> DFxAnula { get; set; }
        public Nullable<System.DateTime> DFiIngresoAnula { get; set; }
        public string CCiUsuarioAnula { get; set; }
        public string CDsEstacionAnula { get; set; }
        public Nullable<int> NIdFaMovimiento { get; set; }
        public string CCiCliente { get; set; }
        public string CCiCanalVenta { get; set; }
        public string CCiVendedor { get; set; }
        public string CSnEnviarCorreo { get; set; }
        public string CSnCorreoEnviado { get; set; }
        public string CDsObservacion { get; set; }
    }
}
