//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCiDetConfigFormulario
    {
        public short NIdVersionFormulario { get; set; }
        public string CCiPlanCta { get; set; }
        public string CNuCasillero { get; set; }
        public short NNuSecuencia { get; set; }
        public short NNuOrden { get; set; }
        public string CCiCuentaDesde { get; set; }
        public string CCiCuentaHasta { get; set; }
        public string CCiTipoAuxiliar { get; set; }
        public string CCiAuxiliar { get; set; }
        public string CCiDpto { get; set; }
        public string CCiProyecto { get; set; }
        public string CCiSubProyecto { get; set; }
    
        public virtual TblCiCabConfigFormulario TblCiCabConfigFormulario { get; set; }
    }
}
