//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCiDetMovimiento
    {
        public int NNuControl { get; set; }
        public int NNuRegistro { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CCiTipoDato { get; set; }
        public string CCiCuenta { get; set; }
        public string CCiTipoAuxiliar { get; set; }
        public string CCiAuxiliar { get; set; }
        public string CCiDpto { get; set; }
        public string CCiProyecto { get; set; }
        public string CCiSubProyecto { get; set; }
        public decimal NNuDebito { get; set; }
        public decimal NNuCredito { get; set; }
        public Nullable<decimal> NNuTercerImporte { get; set; }
        public string CCiUnidadMedida { get; set; }
        public string CDsReferencia { get; set; }
        public string CCiTipoDocCta { get; set; }
        public Nullable<int> NNuNroDocCta { get; set; }
        public Nullable<System.DateTime> DFmFechaDocCta { get; set; }
        public string CCiTipoDocAux { get; set; }
        public Nullable<decimal> NNuNroDocAux { get; set; }
        public Nullable<System.DateTime> DFcAuxiliar { get; set; }
        public Nullable<System.DateTime> DFcFechaVenc { get; set; }
        public string CDsDetalle { get; set; }
        public Nullable<decimal> NNuPrecio { get; set; }
        public string CDsReferencia01 { get; set; }
        public Nullable<int> NIdPrPresupuesto { get; set; }
    }
}
