//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCbDetTransaccionclte
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CciCliente { get; set; }
        public int NCtDocCobranza { get; set; }
        public int NNuFactura { get; set; }
        public string CNuSerieDoc { get; set; }
        public int NNuDocumento { get; set; }
        public int NNuRegistro { get; set; }
        public System.DateTime DfxDocumento { get; set; }
        public string CCiCuenta { get; set; }
        public string CCiTipoAuxiliar { get; set; }
        public string CCiAuxiliar { get; set; }
        public string CCiDpto { get; set; }
        public string CCiProyecto { get; set; }
        public string CCiSubProyecto { get; set; }
        public decimal NNuDebito { get; set; }
        public decimal NNuCredito { get; set; }
        public string CDsReferencia { get; set; }
        public string CDsReferencia01 { get; set; }
        public string CDsDetalle { get; set; }
    }
}
