//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCpTipoDctoPlanilla
    {
        public string CCiTipoDcto { get; set; }
        public string CDsTipoDcto { get; set; }
        public string CCeClaseDcto { get; set; }
        public string CCeTipoDcto { get; set; }
        public string CCtNaturaleza { get; set; }
    }
}
