//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCbCicloFacturaCobro
    {
        public int NIdFaFactura { get; set; }
        public int NNuSecuencia { get; set; }
        public int NIdCbCobro { get; set; }
        public decimal NVtAplicado { get; set; }
        public string CCeCiclo { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CCiEstacionIngreso { get; set; }
        public System.DateTime DFxIngreso { get; set; }
        public string CCiUsuarioAnula { get; set; }
        public string CCiEstacionAnula { get; set; }
        public Nullable<System.DateTime> DFxAnula { get; set; }
        public Nullable<int> NIdCiComprobante { get; set; }
        public string CCeContabilidad { get; set; }
    }
}
