//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCpSelLoteCheque
    {
        public string CCICia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CCindNivel { get; set; }
        public Nullable<decimal> NNuOrdenpago { get; set; }
        public Nullable<decimal> NNuCheque { get; set; }
        public decimal NNuperiodo { get; set; }
        public string CCiAuxiliar { get; set; }
        public string CTxNumDocumento { get; set; }
        public decimal NNucontrol { get; set; }
        public Nullable<decimal> NNuMontoAprueba_ { get; set; }
        public Nullable<decimal> NNuValorPend_ { get; set; }
        public string CDsBeneficiario_ { get; set; }
        public string CDsDetalle_ { get; set; }
        public System.DateTime FechaApru { get; set; }
        public System.DateTime FOrdenpago { get; set; }
        public string CCiBanco_ { get; set; }
        public string CCiCtaCte { get; set; }
        public string CCiCajaBanco_ { get; set; }
        public string CCiCajaCtaCte_ { get; set; }
        public string CCeStatusComp { get; set; }
        public string CCIndInter { get; set; }
        public string CCiUsuarioIng { get; set; }
    }
}
