//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCiSaldoKardex
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public int nnuKardex { get; set; }
        public short NNuRegistro { get; set; }
        public int NNuPresupuesto { get; set; }
        public int NNuSecuenciaPres { get; set; }
        public string CCiTipoPres { get; set; }
        public string CCiProyecto { get; set; }
        public string CCiSubProyecto { get; set; }
        public string CCiTipoInsumo { get; set; }
        public string CCiInsumo { get; set; }
        public string cciTipoDoc { get; set; }
        public int nnuDocumento { get; set; }
        public string cciTipoMov { get; set; }
        public string CCiUnidadMedida { get; set; }
        public decimal NNuCantReal { get; set; }
        public decimal NNuCantTran { get; set; }
        public decimal NNuValNetoReal { get; set; }
        public decimal NNuValNetoTran { get; set; }
        public decimal NNuCantSaldoReal { get; set; }
        public decimal NNuCantSaldoTran { get; set; }
        public decimal NNuCantSaldoDisp { get; set; }
        public decimal NNuValSaldoReal { get; set; }
        public decimal NNuValSaldoTran { get; set; }
        public decimal NNuValSaldoDisp { get; set; }
        public Nullable<System.DateTime> dfxFecha { get; set; }
        public string cceTipoSaldo { get; set; }
        public Nullable<short> NNuRegistroRela { get; set; }
        public string CCiTipoAuxiliar { get; set; }
        public string CCiAuxiliar { get; set; }
        public Nullable<int> NNuSecuenciaDcto { get; set; }
    }
}
