//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCbDetDepositoTransito
    {
        public int NIdCbDepositoTransito { get; set; }
        public int NNuSecDepTrns { get; set; }
        public Nullable<int> NIdCbCobro { get; set; }
        public Nullable<int> NNuSecFormaPago { get; set; }
        public Nullable<decimal> NVtPreDeposito { get; set; }
        public string CCtDocumento { get; set; }
    }
}
