//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCbDetPlantilla
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public short NNuPlantilla { get; set; }
        public short NNuSecuencia { get; set; }
        public string CCiTipoCuenta { get; set; }
        public string CNuSerieRecibero { get; set; }
        public string CSNTodosClientes { get; set; }
        public string CciCliente { get; set; }
        public short NCiTipoCobranza { get; set; }
        public string CCtDebitoCredito { get; set; }
        public string CCiCuenta { get; set; }
        public string CCiTipoAuxiliar { get; set; }
        public string CCiAuxiliar { get; set; }
        public string CCiBanco { get; set; }
        public string CCiCtaCte { get; set; }
        public string CCtOpcionCta { get; set; }
    }
}
