//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCpLoteTransf
    {
        public string ccicia { get; set; }
        public string ccidivision { get; set; }
        public string ccisucursal { get; set; }
        public decimal nnulote { get; set; }
        public decimal nnuvalor { get; set; }
        public string ccestatus { get; set; }
        public System.DateTime dfifechaingreso { get; set; }
        public string cciusuarioingreso { get; set; }
        public Nullable<System.DateTime> dfifechareverso { get; set; }
        public string cciusuarioreverso { get; set; }
    }
}
