//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCpRelTipDocTipCom
    {
        public string Ccicia { get; set; }
        public string CciDivision { get; set; }
        public string CciSucursal { get; set; }
        public string CctCodigoAcceso { get; set; }
        public string CciTipoComprobante { get; set; }
        public string CceRelTipDocTipCom { get; set; }
        public string CTxCodigo { get; set; }
    }
}
