//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCbCabPlantillaContable
    {
        public string CCiCompania { get; set; }
        public string CCidivision { get; set; }
        public string CCiSucursal { get; set; }
        public short CCiPlantilla { get; set; }
        public string CNoPlantilla { get; set; }
        public string CSNProyecto { get; set; }
        public string CSNEnlace { get; set; }
        public string CCePlantilla { get; set; }
        public string CCiTipoComprobante { get; set; }
    }
}
