//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCiPresRealAcum
    {
        public int NNuAnio { get; set; }
        public int NNuPeriodo { get; set; }
        public string CCiCompania { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CCiAuxiliar { get; set; }
        public string CCiCuenta { get; set; }
        public string CCiTipoDato { get; set; }
        public string CCiResponsable { get; set; }
        public decimal NNuDebitoPres { get; set; }
        public decimal NNuCantidadPres { get; set; }
        public decimal NNuDebitoReal { get; set; }
        public decimal NNuCantidadReal { get; set; }
        public decimal NNuAjustado { get; set; }
        public decimal NNuVariacion { get; set; }
        public decimal NNuporcentajeMesA { get; set; }
        public decimal NNuDebitoProyAcum { get; set; }
        public decimal NNuCantidadAcum { get; set; }
        public decimal NNuDebitoRealAcum { get; set; }
        public decimal NNuCantidadRealAcum { get; set; }
        public decimal NNuVariacionAcum { get; set; }
        public decimal NNuPorcentajeAcum { get; set; }
        public string CSNFijaVariable { get; set; }
        public string CCiClaseCosto { get; set; }
    }
}
