//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCpDetMvtoReembolsoCXC
    {
        public int NIdCpMvtoReembolsoCXC { get; set; }
        public int NNuRegistro { get; set; }
        public string CCiCiaDcto { get; set; }
        public string CCiDivisionDcto { get; set; }
        public string CCiSucursalDcto { get; set; }
        public decimal NNuAnioDcto { get; set; }
        public decimal NNuControlDcto { get; set; }
    
        public virtual TblCpCabMvtoReembolsoCXC TblCpCabMvtoReembolsoCXC { get; set; }
    }
}
