//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCbCtaCte
    {
        public string CCiBanco { get; set; }
        public string CCiCtaCte { get; set; }
        public string CCiCompania { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CTxCuenta { get; set; }
        public string NNuCuenta { get; set; }
        public string CTxReferencia { get; set; }
        public string CCeCtaCte { get; set; }
        public string CCtCtaCte { get; set; }
    }
}
