//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCbTransaccionClteExt
    {
        public string CCiCompania { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CciCliente { get; set; }
        public int NNuControlFactura { get; set; }
        public short NCtDocCobranza { get; set; }
        public int NNuDocumento { get; set; }
        public Nullable<System.DateTime> DFvTransaccion { get; set; }
        public Nullable<System.DateTime> DFcTransaccion { get; set; }
        public string CciReferencia1 { get; set; }
        public Nullable<int> NNuDocReferencia1 { get; set; }
        public string CCeTransaccion { get; set; }
        public Nullable<decimal> EVtTransaccion { get; set; }
        public Nullable<decimal> EVtSaldoTransaccion { get; set; }
        public string CCtTransanccion { get; set; }
        public string CDsObservacion { get; set; }
        public System.DateTime DFxIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFxModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
    }
}
