//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCiInsumoOpus
    {
        public string CCiTipoInsumoCi { get; set; }
        public string CCiInsumoOpus { get; set; }
        public string CCiInsumoTempCi { get; set; }
        public string CCiTipoInsumoOpus { get; set; }
        public string CDsInsumoOpus { get; set; }
        public string CCiInsumoCi { get; set; }
    }
}
