//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCiInformePAR
    {
        public string CCiInforme { get; set; }
        public string CCicia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CCiProyecto { get; set; }
        public string CCiSubProyecto { get; set; }
        public Nullable<decimal> NNuNivelCta { get; set; }
        public string cctReporte { get; set; }
        public string cctOrienta { get; set; }
        public string csnLogo { get; set; }
        public string cctDetaResum { get; set; }
        public string csnTotales { get; set; }
        public string CCtNivelImprAux { get; set; }
        public string CCtNivelImprDpto { get; set; }
        public string CCtOrdenImpresionCta { get; set; }
        public string CCtOrdenImpresionAux { get; set; }
        public string CCtOrdenImpresionDpto { get; set; }
        public string CCtOrdenImpresionEstr { get; set; }
        public string CDsEstacion { get; set; }
    }
}
