//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCpComponente
    {
        public string CCiComponente { get; set; }
        public string CNoComponente { get; set; }
        public string CCeComponente { get; set; }
        public Nullable<System.DateTime> DFxIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CCiEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFxModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CCiEstacionModifica { get; set; }
    }
}
