//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCpDetOrdenPago
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public decimal NNuOrdenPago { get; set; }
        public string CCiCiaDcto { get; set; }
        public string CCiDivisionDcto { get; set; }
        public string CCiSucursalDcto { get; set; }
        public decimal NNuAnio { get; set; }
        public decimal NNuControl { get; set; }
        public string CCiUsuarioAprueba { get; set; }
        public decimal NNuMontoAprueba { get; set; }
        public Nullable<decimal> NNuMontoPendienteAnterior { get; set; }
    }
}
