//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCbCabRecap
    {
        public string CCiTarjeta { get; set; }
        public int NNuRecap { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CCtFormaPago { get; set; }
        public decimal NVtDeposito { get; set; }
        public string CCeRecap { get; set; }
        public string CSNMvtoBco { get; set; }
        public string CCiTipoMvto { get; set; }
        public Nullable<System.DateTime> DFxDeposito { get; set; }
        public string NNuAnio { get; set; }
        public Nullable<int> NNuSecuenciaMvtoBco { get; set; }
        public Nullable<System.DateTime> DFxRecap { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public System.DateTime DFxIngreso { get; set; }
        public string CCiUsuarisoModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DFxModifica { get; set; }
        public Nullable<decimal> NVtRetfuente { get; set; }
        public Nullable<decimal> NvtRetIVA { get; set; }
        public string CctPrograma { get; set; }
        public string CCiBancoDeposito { get; set; }
        public string CCiCtaCteDeposito { get; set; }
        public string CCiMotivoBco { get; set; }
        public string CCtContabilizacion { get; set; }
        public string CNuPapeleta { get; set; }
        public Nullable<int> NIdCbDepositoTransito { get; set; }
        public Nullable<decimal> NVtTotalFaltante { get; set; }
        public Nullable<decimal> NVtTotalSobrante { get; set; }
        public Nullable<decimal> NVtTotalIngresos { get; set; }
        public Nullable<decimal> NVtTotalEgresos { get; set; }
    }
}
