//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCiCtaDetCteRelacionada
    {
        public string CCiBanco { get; set; }
        public string CCiCtaCte { get; set; }
        public int NNuRegistro { get; set; }
        public string CCiBancoRel { get; set; }
        public string CCiCtaCteRel { get; set; }
    }
}
