//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCbDetLoteNDDonacion
    {
        public int NIdLoteNDDonacion { get; set; }
        public int NNuSecuencia { get; set; }
        public string CCiCliente { get; set; }
        public Nullable<decimal> NVtValorDonacion { get; set; }
        public Nullable<short> NCtDocCobranza { get; set; }
        public Nullable<int> NNuDocumento { get; set; }
        public string CCiCuenta { get; set; }
        public string CCiTipoAuxiliar { get; set; }
        public string CCiAuxiliar { get; set; }
        public Nullable<System.DateTime> DFxFechaEmision { get; set; }
        public Nullable<System.DateTime> DFxFechaVcmto { get; set; }
    }
}
