//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCbRelCobroOrdenes
    {
        public int NnuControl { get; set; }
        public string CciCompania { get; set; }
        public string CciDivision { get; set; }
        public string CciSucursal { get; set; }
        public string CctOrden { get; set; }
        public string CNuSecuencia { get; set; }
        public string CciCliente { get; set; }
        public string CnoContactoRefencia { get; set; }
        public string CceOrden { get; set; }
        public int NnuControlCobro { get; set; }
        public int NnuControlFactura { get; set; }
        public System.DateTime DfxEmision { get; set; }
        public string CDxObservacion { get; set; }
        public string CDsReferencia { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DfxIngreso { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CdsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DfxModifica { get; set; }
    }
}
