//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCbDetPlantillaCobranza
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public short NNuPlantilla { get; set; }
        public short NNuSecuencia { get; set; }
        public string CCiProyecto { get; set; }
        public short CCiTipoCobranza { get; set; }
        public string CCiModulo { get; set; }
        public short CCiTipoDocumento { get; set; }
        public string CCiMotivo { get; set; }
        public string CCtDebitoCredito { get; set; }
        public string CCiCuenta { get; set; }
        public string CCiTipoAuxiliar { get; set; }
        public string CCiAuxiliar { get; set; }
    }
}
