//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCiCabMvtosBcos
    {
        public string CciCia { get; set; }
        public string CciDivision { get; set; }
        public string CciSucursal { get; set; }
        public string CCiTipoMvto { get; set; }
        public decimal NNuSecuencia { get; set; }
        public decimal NNuAnio { get; set; }
        public string CCiBanco { get; set; }
        public string CCiCtaCte { get; set; }
        public string CCiAuxiliar { get; set; }
        public System.DateTime DFmFecDocum { get; set; }
        public string CDsConcepto { get; set; }
        public string NNuCheque { get; set; }
        public decimal NNuValorEfectivo { get; set; }
        public decimal NNuValorCheque { get; set; }
        public decimal NNuValor { get; set; }
        public string CCtManual { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public System.DateTime DFiFechaIngreso { get; set; }
        public string CCeConcilia { get; set; }
        public string CCeMvto { get; set; }
        public Nullable<System.DateTime> FFxContabiliza { get; set; }
        public string CtxInterComp { get; set; }
        public string CCiCodInter { get; set; }
        public string CCtOrigenMvto { get; set; }
        public string CCiMotivo { get; set; }
        public string CCeComprobante { get; set; }
        public Nullable<System.DateTime> DFxRegistro { get; set; }
        public string CSNLote { get; set; }
        public string CDsReferencia { get; set; }
        public string CDsRecibidoDe { get; set; }
        public Nullable<decimal> NNuValorTarjeta { get; set; }
        public Nullable<short> NNuImpresion { get; set; }
        public string CCiProveedor { get; set; }
        public string CSNAnticipo { get; set; }
        public string CCeAnticipo { get; set; }
        public string CSNInterdivision { get; set; }
        public int NNuControlInterdivision { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public Nullable<System.DateTime> DFcFechaModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public string CCtProveedorCliente { get; set; }
        public Nullable<int> NNuAnticipo { get; set; }
        public Nullable<decimal> NNuValorAbonado { get; set; }
        public Nullable<int> NNuControlComprobante { get; set; }
        public string CCiCiaBatch { get; set; }
        public string CCiDivisionBatch { get; set; }
        public string CCiSucursalBatch { get; set; }
        public string CCiTipoComprobanteBatch { get; set; }
        public Nullable<short> NNuAnioBatch { get; set; }
        public Nullable<short> NNuPeriodoBatch { get; set; }
        public Nullable<int> NNuComprobanteBatch { get; set; }
        public Nullable<int> NIdCiMovimientoAnticipo { get; set; }
        public Nullable<short> NCiTipoCobranzaAnticipo { get; set; }
        public Nullable<int> NIdFaContrato { get; set; }
        public string CCiDpto { get; set; }
        public Nullable<int> NIdPrPresupuesto { get; set; }
        public string CciTipoAnticipo { get; set; }
    }
}
