//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCpLoteTransfBzdes
    {
        public string ccicia { get; set; }
        public string ccidivision { get; set; }
        public string ccisucursal { get; set; }
        public decimal nnulote { get; set; }
        public decimal nnuordenpago { get; set; }
        public decimal nnuaniodcto { get; set; }
        public decimal nnucontroldcto { get; set; }
        public string tipo { get; set; }
        public string secuencial { get; set; }
        public string tipo_rubro { get; set; }
        public string cod_doc { get; set; }
        public string concepto { get; set; }
        public string valor { get; set; }
        public string base_impo { get; set; }
        public string signo { get; set; }
        public string porcentaje { get; set; }
        public string f_inicio { get; set; }
        public string f_vigencia { get; set; }
        public string bandera_co { get; set; }
        public string bandera_re { get; set; }
        public string bandera_iv { get; set; }
        public string referencia { get; set; }
    }
}
