//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCiCtaCte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCiCtaCte()
        {
            this.TblBcCtaCteServContratado = new HashSet<TblBcCtaCteServContratado>();
            this.TblCiCtaCteRelGrupoObra = new HashSet<TblCiCtaCteRelGrupoObra>();
        }
    
        public string CCiBanco { get; set; }
        public string CCiCtaCte { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CTxCuenta { get; set; }
        public Nullable<decimal> NNuCuenta { get; set; }
        public string CtxReferencia { get; set; }
        public Nullable<decimal> NNuSaldoInicial { get; set; }
        public decimal NNuSaldoActual { get; set; }
        public string CCiTipoComprobante { get; set; }
        public string CCiCuenta { get; set; }
        public string CCiTipoAuxiliar { get; set; }
        public string CCiAuxiliar { get; set; }
        public string CCeCtaCte { get; set; }
        public string CCtChequeManuAuto { get; set; }
        public decimal NNuSecuenciaCheque { get; set; }
        public string CCtCajaBanco { get; set; }
        public Nullable<System.DateTime> DFxUltimoCierre { get; set; }
        public decimal NNuSaldoUltimoCierre { get; set; }
        public Nullable<decimal> NNuSaldoLibrosUltimaConc { get; set; }
        public Nullable<decimal> NNuSaldoBancoUltimaConc { get; set; }
        public decimal NNuLongitudBeneficiario { get; set; }
        public string CCtIdioma { get; set; }
        public string CSNEgresoEfectivo { get; set; }
        public string CCiTipoComprobanteEfectivo { get; set; }
        public string CCtConciliacion { get; set; }
        public string CCtOrigen { get; set; }
        public string CDsAbreviatura { get; set; }
        public string CdsDireccion1 { get; set; }
        public string CdsDireccion2 { get; set; }
        public string CDsGlosa { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFiIngreso { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DFmModifica { get; set; }
        public string CSnGeneraUnaNDxTransf { get; set; }
        public string CdsDirArchivoTransf { get; set; }
        public string CSnPagoElectronico { get; set; }
        public string CCeNDBanacaria { get; set; }
        public string CCiTipoMvtoBco { get; set; }
        public string CCiMotivoBco { get; set; }
        public string CCtInstanciaGeneraNDB { get; set; }
        public string CCtImpresionCheque { get; set; }
        public string CSnCtaPadre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBcCtaCteServContratado> TblBcCtaCteServContratado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCiCtaCteRelGrupoObra> TblCiCtaCteRelGrupoObra { get; set; }
    }
}
