//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCbDetBajaSaldo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCbDetBajaSaldo()
        {
            this.TblCbDistribuyeMasivo = new HashSet<TblCbDistribuyeMasivo>();
        }
    
        public int NIdCbLoteSaldo { get; set; }
        public int NNuSecuencia { get; set; }
        public string CciCliente { get; set; }
        public short NCtDocCobranza { get; set; }
        public Nullable<int> NNuFactura { get; set; }
        public string CNuSerieDoc { get; set; }
        public Nullable<int> NNuDocumento { get; set; }
        public short NNuCuota { get; set; }
        public short NNuDias { get; set; }
        public System.DateTime DFvTransaCCion { get; set; }
        public decimal NVtDocumento { get; set; }
        public decimal NVtSaldo { get; set; }
        public decimal NVtMora { get; set; }
        public decimal NVtTotal { get; set; }
        public string CCiUsuario { get; set; }
        public Nullable<decimal> NVtRetencionFte { get; set; }
        public Nullable<decimal> NVtRetencionIva { get; set; }
        public Nullable<decimal> NVtRetencionNC { get; set; }
        public Nullable<decimal> NVtOtros { get; set; }
        public Nullable<decimal> NVtaCobrar { get; set; }
        public Nullable<int> NIdCbCobro { get; set; }
        public Nullable<int> NNuCobro { get; set; }
        public string CCiCompaniaTrans { get; set; }
        public string CCiDivisionTrans { get; set; }
        public string CCiSucursalTrans { get; set; }
        public Nullable<short> NCtDocCobranzaTrans { get; set; }
        public Nullable<int> NNuFacturaTrans { get; set; }
        public string CNuSerieDocTrans { get; set; }
        public Nullable<int> NNuDocumentoTrans { get; set; }
        public Nullable<int> NNuAnioTrans { get; set; }
        public string CCiVendedor { get; set; }
        public Nullable<int> NNuSecuenciaDetalle { get; set; }
        public Nullable<decimal> NVtExcedenteAplicado { get; set; }
        public string CSnTransaccionAutomatica { get; set; }
    
        public virtual TblCbCabBajaSaldo TblCbCabBajaSaldo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCbDistribuyeMasivo> TblCbDistribuyeMasivo { get; set; }
    }
}
