//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExLiqMaterialesEmbarca
    {
        public int NNuIdLiquidaMateriales { get; set; }
        public int NNuIdLiqMaterialesEmbarca { get; set; }
        public string CCiProductoMaterial { get; set; }
        public string CCiProducto { get; set; }
        public Nullable<decimal> NNuCantProducto { get; set; }
        public Nullable<decimal> NNuCantReal { get; set; }
        public Nullable<decimal> NNuCantDosificacion { get; set; }
    }
}
