//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExDosificacionMaterialEmpaque
    {
        public string CCiProducto { get; set; }
        public string CCiProductoMaterial { get; set; }
        public string CiModoExplosion { get; set; }
        public string CCiUnidadMedida { get; set; }
        public Nullable<decimal> NQnCantidad { get; set; }
        public string CCeEstado { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFiIngreso { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DFmModifica { get; set; }
    
        public virtual TblCiUnidadMedida TblCiUnidadMedida { get; set; }
        public virtual TblIvProducto TblIvProducto { get; set; }
        public virtual TblIvProducto TblIvProducto1 { get; set; }
    }
}
