//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExCiaTransporte
    {
        public short NIdCiaTransporte { get; set; }
        public string CCiCiaTransporte { get; set; }
        public string CNoCiaTransporte { get; set; }
        public string CCeCiaTransporte { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public System.DateTime DFiIngreso { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DFmModifica { get; set; }
        public string CSnCiaRelacionada { get; set; }
        public string CDsContacto { get; set; }
        public string CDsDireccion { get; set; }
        public string CCiIdentificacion { get; set; }
        public string CNuTelefono { get; set; }
        public string CDsObservacion { get; set; }
    }
}
