//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExPrecioProducto
    {
        public Nullable<int> NNuControlPrecio { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public Nullable<int> NNuSecuencia { get; set; }
        public Nullable<int> NNuSemana { get; set; }
        public string CCiProducto { get; set; }
        public string CCiProveedor { get; set; }
        public Nullable<int> NNuCajas { get; set; }
        public Nullable<decimal> NNuPrecioOficial { get; set; }
        public Nullable<decimal> NNuPrecioPactado { get; set; }
        public Nullable<decimal> NNuSubtotal { get; set; }
        public Nullable<int> NNuTramite { get; set; }
        public Nullable<int> NNuCargaProd { get; set; }
        public string CNuContenedor { get; set; }
        public string CCeEstado { get; set; }
        public Nullable<int> NNuLiquidaFrutas { get; set; }
        public Nullable<System.DateTime> DfxFechaIngreso { get; set; }
        public string CCiEstacionIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public Nullable<System.DateTime> DfxFechaModifica { get; set; }
        public string CCiEstacionModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public Nullable<decimal> NNuComision { get; set; }
        public string CDsBeneficiarioComis { get; set; }
    }
}
