//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEdDetExpreso
    {
        public string CCiIdExpreso { get; set; }
        public string CCiIdDetExpreso { get; set; }
        public string CNoDetExpreso { get; set; }
        public Nullable<decimal> NNuValorExpreso { get; set; }
        public string CdsChofer { get; set; }
        public string CdsDescripcion { get; set; }
    }
}
