//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLExBuque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLExBuque()
        {
            this.TBLExCabTramiteExportacion = new HashSet<TBLExCabTramiteExportacion>();
            this.TblHcCajaEnviada = new HashSet<TblHcCajaEnviada>();
        }
    
        public short NidBuque { get; set; }
        public Nullable<short> NIdNaviera { get; set; }
        public string CNombreBuque { get; set; }
        public string CEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLExCabTramiteExportacion> TBLExCabTramiteExportacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHcCajaEnviada> TblHcCajaEnviada { get; set; }
    }
}
