//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExCabControlPrecios
    {
        public int NIdControl { get; set; }
        public short NIdPeriodo { get; set; }
        public short NQnProducto { get; set; }
        public Nullable<decimal> NQnCajas { get; set; }
        public Nullable<decimal> NVCostoOficial { get; set; }
        public Nullable<decimal> NVCostoPactado { get; set; }
        public Nullable<decimal> NvtSubTotal { get; set; }
        public Nullable<bool> CCeTodosProducto { get; set; }
        public string CCeEstado { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFIngreso { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DFmModifica { get; set; }
    
        public virtual TblExCabControlPrecios TblExCabControlPrecios1 { get; set; }
        public virtual TblExCabControlPrecios TblExCabControlPrecios2 { get; set; }
    }
}
