//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExLiqMateriales
    {
        public int NNuIdLiquidaMateriales { get; set; }
        public int NNuSecuencia { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public Nullable<int> NIdTramite { get; set; }
        public string CCiProveedor { get; set; }
        public string CCiProducto { get; set; }
        public string CCiUnidadMedida { get; set; }
        public Nullable<decimal> NNuCantidad { get; set; }
        public Nullable<decimal> NNuPrecio { get; set; }
        public Nullable<decimal> NNuTotal { get; set; }
        public Nullable<decimal> NNuTotalPactado { get; set; }
        public Nullable<int> NNuLiquidaFrutas { get; set; }
        public Nullable<int> NNuTransferNegativo { get; set; }
        public Nullable<int> NNuTransferPositivo { get; set; }
        public Nullable<int> NNuEgreso { get; set; }
        public string CCeEstado { get; set; }
        public Nullable<System.DateTime> DfxFechaIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CCiEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DfxFechaModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CCiEstacionModifica { get; set; }
        public Nullable<decimal> NQnDevuelveProveedor { get; set; }
        public Nullable<decimal> NQnCobraraProveedor { get; set; }
        public Nullable<int> NIdIvTransfEnvioDev { get; set; }
        public Nullable<int> NIdIvMovimientoEGConsumo { get; set; }
        public Nullable<int> NIdIvMovimientoEGVenta { get; set; }
        public Nullable<decimal> NNuPrecioPromedio { get; set; }
        public Nullable<decimal> NNuTotalDevolucion { get; set; }
        public Nullable<int> NNuidPeriodo { get; set; }
    }
}
