//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFaRelFacturaNCND
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public decimal NNuControlNDNC { get; set; }
        public decimal NNuSecuenciaNCND { get; set; }
        public string CCtNCND { get; set; }
        public decimal NNuControlFactura { get; set; }
        public decimal NNuSecuenciaFactura { get; set; }
        public string CCeDocumento { get; set; }
        public decimal NNuValorAbono { get; set; }
        public decimal NNuTotalAbonado { get; set; }
        public System.DateTime DFxAplica { get; set; }
        public string CCiUsuario { get; set; }
        public string CDsEstacion { get; set; }
        public string CCeAplicacion { get; set; }
        public Nullable<System.DateTime> DFxAnula { get; set; }
        public string CCiUsuarioAnula { get; set; }
        public string CDsEstacionAnula { get; set; }
        public Nullable<int> NCtDocCobranza { get; set; }
    }
}
