//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFaDetallePlan
    {
        public short NNuIdPlan { get; set; }
        public string CCiContexto { get; set; }
        public short NNuIdOperador { get; set; }
        public Nullable<decimal> NNuPrecio { get; set; }
        public Nullable<decimal> NNuCosto { get; set; }
        public string CCeEstado { get; set; }
    
        public virtual TblFaContexto TblFaContexto { get; set; }
        public virtual TblFaOperador TblFaOperador { get; set; }
        public virtual TblFaPlan TblFaPlan { get; set; }
    }
}
