//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFaCabGuiaRemision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFaCabGuiaRemision()
        {
            this.TblFaDetGuiaRemision = new HashSet<TblFaDetGuiaRemision>();
        }
    
        public int NIdFaGuiaRemision { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public int NNuGuiaRemision { get; set; }
        public string CNuSerie { get; set; }
        public string CNuSecuencia { get; set; }
        public string CNuAutorizacion { get; set; }
        public string CNuCamion { get; set; }
        public string CCiIdentificacionChofer { get; set; }
        public string CtXPartida { get; set; }
        public System.DateTime DfxEmision { get; set; }
        public decimal NVtGuiaRemision { get; set; }
        public string CCeGuiaRemision { get; set; }
        public System.DateTime DFiIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFmModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public string CCiMotivo { get; set; }
        public Nullable<System.DateTime> DFxTrasladoIni { get; set; }
        public Nullable<System.DateTime> DFxTrasladoFin { get; set; }
        public Nullable<System.DateTime> DFxCaducidad { get; set; }
        public string CDsRucCiaTransp { get; set; }
        public string CDsCiaTransp { get; set; }
        public string CDsPlaca { get; set; }
        public string CDsCarro { get; set; }
        public string CCtFormaEmisionDcto { get; set; }
        public string CCtServicioConsume { get; set; }
        public string CCiClaveAcceso { get; set; }
        public string CSnAutorizado { get; set; }
        public Nullable<System.DateTime> DFxAutorizacion { get; set; }
        public string CCiMensajeWS { get; set; }
        public string CDsMensajeWS { get; set; }
        public string CDsMensajeAdicionalWS { get; set; }
        public string CSnGenerado { get; set; }
        public string CSnXMLValidado { get; set; }
        public string CSnFirmado { get; set; }
        public string CSnCorreoDEEnviado { get; set; }
        public string CCiAmbienteEmisionDctoElectronico { get; set; }
        public string CCtDisponibilidadSistemaSRI { get; set; }
        public string CSnXMLDevuelto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFaDetGuiaRemision> TblFaDetGuiaRemision { get; set; }
    }
}
