//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFaCabNotaEntrega
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLFaCabNotaEntrega()
        {
            this.TBLFaDetNotaEntrega = new HashSet<TBLFaDetNotaEntrega>();
        }
    
        public int NNuControl { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public int NNuNotaEntrega { get; set; }
        public string CCiLineaProd { get; set; }
        public string CciCliente { get; set; }
        public Nullable<int> NNuFactura { get; set; }
        public Nullable<int> NNuGuiaRemision { get; set; }
        public Nullable<int> NNuNotaRecepcion { get; set; }
        public Nullable<int> NNuCotizacion { get; set; }
        public Nullable<System.DateTime> DFxEntrega { get; set; }
        public string CCeActivo { get; set; }
        public string CCeFactura { get; set; }
        public System.DateTime DFxIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public System.DateTime DFxModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public string CDxObservacion { get; set; }
        public string CDxReferencia { get; set; }
        public string CCiDpto { get; set; }
        public Nullable<System.DateTime> DfxRegistro { get; set; }
        public Nullable<int> NNuControlInv { get; set; }
        public string CSnAplicaDimensiones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFaDetNotaEntrega> TBLFaDetNotaEntrega { get; set; }
    }
}
