//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFaCabProforma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFaCabProforma()
        {
            this.TblFaDetProforma = new HashSet<TblFaDetProforma>();
        }
    
        public int NNuControl { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public int NNuProforma { get; set; }
        public short NNuAnio { get; set; }
        public System.DateTime DFxMovimiento { get; set; }
        public int NNuProformaRef { get; set; }
        public string CCiBodegaEnv { get; set; }
        public string CCiUbicacionEnv { get; set; }
        public string CCiMotivoEnv { get; set; }
        public Nullable<int> NIdPrPresupuestoEnvio { get; set; }
        public decimal NVtMontoTotal { get; set; }
        public string CCiBodegaRecibe { get; set; }
        public string CCiUbicacionRecibe { get; set; }
        public string CCiMotivoRecibe { get; set; }
        public Nullable<int> NIdPrPresupuestoRecibe { get; set; }
        public decimal NVtMontoTotalRecibe { get; set; }
        public Nullable<int> NIdSubCliente { get; set; }
        public Nullable<int> NIdAgencia { get; set; }
        public string CciCliente { get; set; }
        public string CCiTipoPrecioProducto { get; set; }
        public string CDsObservacion { get; set; }
        public string CSNGuiaRemision { get; set; }
        public Nullable<int> NIdIvGuiaRemision { get; set; }
        public Nullable<decimal> NVtBrutoBaseIva { get; set; }
        public Nullable<decimal> NNuPorcDsctoBaseIva { get; set; }
        public Nullable<decimal> NNuValDsctoBaseIva { get; set; }
        public Nullable<decimal> NNuSubTotalBaseIva { get; set; }
        public Nullable<decimal> NVtBrutoBaseCero { get; set; }
        public Nullable<decimal> NNuPorcDsctoBaseCero { get; set; }
        public Nullable<decimal> NNuValDsctoBaseCero { get; set; }
        public Nullable<decimal> NNuSubTotalBase0 { get; set; }
        public Nullable<decimal> NVtMontoBruto { get; set; }
        public Nullable<decimal> NNuPorDescuento { get; set; }
        public decimal NNuValDescuento { get; set; }
        public Nullable<decimal> NNuSubTotalNeto { get; set; }
        public decimal NNuPorIVA { get; set; }
        public decimal NNuValIVA { get; set; }
        public decimal NNuTotalxPagar { get; set; }
        public string CSnAjusteIva { get; set; }
        public string CCtAjusteIva { get; set; }
        public Nullable<decimal> NVtAjusteIva { get; set; }
        public string CSnLeySolidaria { get; set; }
        public Nullable<decimal> NNuPorIVACompensacion { get; set; }
        public Nullable<decimal> NNuValIVACompensacion { get; set; }
        public string CCeProforma { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public System.DateTime DFiIngreso { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DFmModifica { get; set; }
        public Nullable<int> NNuMvtoEgresoEnv { get; set; }
        public Nullable<int> NNuMvtoIngresoRecibe { get; set; }
        public Nullable<int> NNuMvtoEgresoConsig { get; set; }
        public string CTxDireccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFaDetProforma> TblFaDetProforma { get; set; }
    }
}
