//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFaPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFaPlan()
        {
            this.TblFaActualizaPlanCuenta = new HashSet<TblFaActualizaPlanCuenta>();
            this.TblFaDetallePlan = new HashSet<TblFaDetallePlan>();
            this.TblFaPlanCuenta = new HashSet<TblFaPlanCuenta>();
        }
    
        public short NNuIdPlan { get; set; }
        public string CCiPlan { get; set; }
        public string CDsPlan { get; set; }
        public string CCtPlan { get; set; }
        public string CCtValido { get; set; }
        public string CCiTerminoPago { get; set; }
        public decimal NNuCostoBasico { get; set; }
        public int NNuMinutosIncluidos { get; set; }
        public decimal NNuValorMinutosIncluidos { get; set; }
        public decimal NNuCostoLinea { get; set; }
        public decimal NNuCostoInstalacion { get; set; }
        public string CSNLineaAdicional { get; set; }
        public decimal NNuCostoAdicionalLinea { get; set; }
        public string CSNExpiraMinutos { get; set; }
        public string CSNPlanControlado { get; set; }
        public string CCePlan { get; set; }
        public System.DateTime DFxIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public Nullable<System.DateTime> DFxModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public string CCiDescCostInicial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFaActualizaPlanCuenta> TblFaActualizaPlanCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFaDetallePlan> TblFaDetallePlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFaPlanCuenta> TblFaPlanCuenta { get; set; }
    }
}
