//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFaTdmPuerto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFaTdmPuerto()
        {
            this.TblFaLineaTelefonica = new HashSet<TblFaLineaTelefonica>();
        }
    
        public short NNuIdPuerto { get; set; }
        public Nullable<int> NNuPuerto { get; set; }
        public string CDsPuerto { get; set; }
        public Nullable<short> NNuIdCard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFaLineaTelefonica> TblFaLineaTelefonica { get; set; }
        public virtual TblFaTdmCard TblFaTdmCard { get; set; }
    }
}
