//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFaDetNotaPedido
    {
        public int NIdFaNotaPedido { get; set; }
        public int NNuSecuencia { get; set; }
        public string CCiProducto { get; set; }
        public string CCiUnidadVenta { get; set; }
        public Nullable<decimal> NNuPesoNeto { get; set; }
        public Nullable<decimal> NNuUnidad { get; set; }
        public Nullable<decimal> NNuPeso { get; set; }
        public Nullable<decimal> NNuPesoEquivalente { get; set; }
        public string CsnPesado { get; set; }
        public Nullable<decimal> NNuPesado { get; set; }
        public Nullable<decimal> NNuDespachado { get; set; }
        public string CSnRequerido { get; set; }
        public Nullable<int> NIdOcRequerimiento { get; set; }
    
        public virtual TblFaCabNotaPedido TblFaCabNotaPedido { get; set; }
    }
}
