//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFaCabControlPaquete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFaCabControlPaquete()
        {
            this.TblFaDetControlPaquete = new HashSet<TblFaDetControlPaquete>();
        }
    
        public int NIdFaControlPaquete { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public int NNuControlPaquete { get; set; }
        public string CCtCantidadValor { get; set; }
        public decimal NVtFacturado { get; set; }
        public decimal NVtConsumido { get; set; }
        public int NIdFaFactura { get; set; }
        public string NNuSecuenciaFact { get; set; }
        public System.DateTime DFxVencimiento { get; set; }
        public string CCeEstado { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CCiEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFxIngreso { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CCiEstacionModifica { get; set; }
        public Nullable<System.DateTime> DFxModifica { get; set; }
        public Nullable<System.DateTime> DFxCierre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFaDetControlPaquete> TblFaDetControlPaquete { get; set; }
    }
}
