//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFaConfigRecarga
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CCiProducto { get; set; }
        public string CCiBodega { get; set; }
        public string CCiUbicacion { get; set; }
        public string CNuSerieFactura { get; set; }
        public Nullable<short> NCtDocCobranzaDeposito { get; set; }
        public System.DateTime DFxIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CCiEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFxModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CCiEstacionModifica { get; set; }
        public string CCiVendedor { get; set; }
        public string CCiTipoFact { get; set; }
        public string CCiCanalVenta { get; set; }
        public string CCiVendedorRuta { get; set; }
    }
}
