//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGeTablaReplicar
    {
        public string CCiTablaReplicar { get; set; }
        public string CNoTabla { get; set; }
        public short NNuOrden { get; set; }
        public string CCtModulo { get; set; }
        public string CDsDescripcion { get; set; }
        public string CCeTablaReplicar { get; set; }
        public string CSNContabilidad { get; set; }
        public string CCiCampoRelacionaReplicacion { get; set; }
        public string CNoCampoControlComprobante { get; set; }
    }
}
