//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGRDatosTecnicos
    {
        public string ccicia { get; set; }
        public string ccidivision { get; set; }
        public string ccianio { get; set; }
        public string ccimes { get; set; }
        public string cciccosto { get; set; }
        public string cciCodDT { get; set; }
        public string cnoDtecnico { get; set; }
        public Nullable<decimal> cciReal { get; set; }
        public Nullable<decimal> ccipresupuestado { get; set; }
        public string cciOrdenImpr { get; set; }
        public Nullable<int> ccidatosT { get; set; }
    }
}
