//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblgeContactoReferenciaLaboral
    {
        public string CciTipoIdentificacion { get; set; }
        public string CciDocumento { get; set; }
        public int NnuControl { get; set; }
        public string CtxEmpresaAnterior { get; set; }
        public string CtxCargo { get; set; }
        public string CtxAntiguedad { get; set; }
        public string CtxDireccion { get; set; }
        public string CtxSector { get; set; }
        public string CtxCiudad { get; set; }
        public string CtxTelefono1 { get; set; }
        public string CtxTelefono2 { get; set; }
    }
}
