//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGecontacto
    {
        public string ccitipoidentificacion { get; set; }
        public string ccidocumento { get; set; }
        public string ctxnombres { get; set; }
        public string ctxapellido1 { get; set; }
        public string ctxapellido2 { get; set; }
        public string cceestadocivil { get; set; }
        public string cctsexo { get; set; }
        public string cnonacionalidad { get; set; }
        public string ctxtelefono1 { get; set; }
        public string ctxtelefono2 { get; set; }
        public Nullable<System.DateTime> dfenacimiento { get; set; }
        public string ctxprofesion { get; set; }
        public Nullable<decimal> nqncargas { get; set; }
        public string ctxdireccion { get; set; }
        public string ctxfax { get; set; }
        public string ctxcelular { get; set; }
        public string ctxcasilla { get; set; }
        public string cnociudad { get; set; }
        public string cnoparroquia { get; set; }
        public string ctxemail { get; set; }
        public string cctenviocorresp { get; set; }
        public string cctnivelestudio { get; set; }
        public string csnresidExt { get; set; }
        public string ctxdireccionExt { get; set; }
        public string ctxtelefonosExt { get; set; }
        public string ccitipoidentificaCony { get; set; }
        public string ccidocumentoCony { get; set; }
        public string cnoconyuge { get; set; }
        public string cnonacionalidadCony { get; set; }
        public string ctxdireccionCony { get; set; }
        public string cnutelf1Cony { get; set; }
        public string cnutelf2Cony { get; set; }
        public string ctxemailCony { get; set; }
        public string csnResidExtCony { get; set; }
        public string ctxdireccionExtCony { get; set; }
        public string ctxtelefonosExtCony { get; set; }
        public string cnofamiliar { get; set; }
        public string cnutelffamiliar { get; set; }
        public string cnutelf2familiar { get; set; }
        public string cnociudadfamiliar { get; set; }
        public string cnodireccionfamiliar { get; set; }
        public Nullable<System.DateTime> dfeingreso { get; set; }
        public string cnouseringresa { get; set; }
        public Nullable<System.DateTime> dfemodifica { get; set; }
        public string cnousermodifica { get; set; }
        public string ccioficial { get; set; }
        public string csnseparaBienes { get; set; }
        public string ccioficialcred { get; set; }
        public string cctvivienda { get; set; }
        public Nullable<int> nqnedad { get; set; }
        public string cnolugarnacCony { get; set; }
        public Nullable<System.DateTime> dfenacCony { get; set; }
        public Nullable<int> nqnedadCony { get; set; }
        public string csnCamaraCom { get; set; }
        public string cnoperJuridica { get; set; }
        public string cnorepJuridica { get; set; }
        public string CCiAuxiliar { get; set; }
        public string CCiCuenta { get; set; }
        public string nqnafiliaCC { get; set; }
        public string csnAfiliaIESS { get; set; }
        public Nullable<decimal> nqntiempoAfilia { get; set; }
        public string ctxtipomoneda { get; set; }
        public string ctxprofesionCony { get; set; }
        public string ctxzona { get; set; }
        public string ctxtipoauxiliar { get; set; }
        public string ctxcomentariocredito { get; set; }
        public string csncredito { get; set; }
        public string CsnResLegIleg { get; set; }
        public string CtxObsLegIleg { get; set; }
        public string CsnResLegIlegCony { get; set; }
        public string CtxObsLegIlegCony { get; set; }
        public string CtxConclusion { get; set; }
        public string ctxRazonSocial { get; set; }
        public byte[] GlgImagen { get; set; }
        public byte[] GlgImagenCony { get; set; }
        public string CciCalificacion { get; set; }
        public string ccievento { get; set; }
        public string ccimedio { get; set; }
        public string cciacercamiento { get; set; }
        public string CtxApellido1Referido { get; set; }
        public string CtxApellido2Referido { get; set; }
        public string CtxNombresReferido { get; set; }
        public string CciCiudad { get; set; }
        public string CciParroquia { get; set; }
        public string cciFinanciera { get; set; }
        public string CDxContacto { get; set; }
        public string CCeTieneCredito { get; set; }
        public Nullable<decimal> NNuValorCredito { get; set; }
        public Nullable<decimal> NNuPorcDesc { get; set; }
    }
}
