//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGeComisionProducto
    {
        public string CCiProducto { get; set; }
        public short NNuSecuencia { get; set; }
        public string CSNVigente { get; set; }
        public System.DateTime DFxVencimiento { get; set; }
        public decimal NNuPorcComision { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CCiEstacionModifica { get; set; }
        public System.DateTime DFxModifica { get; set; }
    }
}
