//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGeRutaVisitaCliente
    {
        public string CCiRutaVisitaCliente { get; set; }
        public string CNoRutaVisitaCliente { get; set; }
        public string CSnLunes { get; set; }
        public string CSnMartes { get; set; }
        public string CSnMiercoles { get; set; }
        public string CSnJueves { get; set; }
        public string CSnViernes { get; set; }
        public string CSnSabado { get; set; }
        public string CSnDomingo { get; set; }
        public string CCeRutaVisitaCliente { get; set; }
    }
}
