//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGeDetCertificadoDigital
    {
        public int NIdGeCertificadoDigital { get; set; }
        public int NNuRegistro { get; set; }
        public string CCiUsuario { get; set; }
        public string CCiCia { get; set; }
        public string CTxRuta { get; set; }
        public string CTxClave { get; set; }
        public Nullable<System.DateTime> DFxCaducidad { get; set; }
        public Nullable<int> NNuDiaIniNotificaxVencer { get; set; }
    }
}
