//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGeDetCruceCuenta
    {
        public long NIdCruceCuenta { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CNuSerieRecibero { get; set; }
        public string CCiTipoComprobante { get; set; }
        public Nullable<short> NCiTipoCobranza { get; set; }
        public string CCeCruceCuenta { get; set; }
    }
}
