//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGeTipoProveedor
    {
        public string CCiTipoProveedor { get; set; }
        public string CNoTipoProveedor { get; set; }
        public string CCeTipoProveedor { get; set; }
        public string CsnCamaronero { get; set; }
        public string CsnTransportista { get; set; }
    }
}
