//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHcCabEnvioCarga
    {
        public int NIdHcEnvioCarga { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public int NNuControl { get; set; }
        public string CciCliente { get; set; }
        public System.DateTime DFxEnvioCarga { get; set; }
        public int NIdHcPeriodo { get; set; }
        public string CNuRequerimiento { get; set; }
        public System.DateTime DFxViaje { get; set; }
        public string CCiCiudadCarga { get; set; }
        public int NIdPuertoCarga { get; set; }
        public string CCiCiudadDescarga { get; set; }
        public int NIdPuertoDescarga { get; set; }
        public string CTxProductoTransportar { get; set; }
        public int NIdCiaTransporte { get; set; }
        public string CCiTransportista { get; set; }
        public string CCiTipoVehiculo { get; set; }
        public string CTxPlaca { get; set; }
        public string CTxRuta { get; set; }
        public string CCiDocumentacion { get; set; }
        public string CNuContenedor { get; set; }
        public string CTxSello1 { get; set; }
        public string CTxSello2 { get; set; }
        public string CTxSello3 { get; set; }
        public string CNuGenerador { get; set; }
        public string CTxObservacion { get; set; }
        public string CCeEnvioCarga { get; set; }
        public string CCeFactura { get; set; }
        public System.DateTime DFxIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFxModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
    }
}
