//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHcCajaEnviada
    {
        public int NIdHcCajaEnviada { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public int NNuControl { get; set; }
        public int NIdHcProduccion { get; set; }
        public string CCiProducto { get; set; }
        public string CciCliente { get; set; }
        public string CNuGuia { get; set; }
        public string CTxCodigo { get; set; }
        public string CTxPlacaCamion { get; set; }
        public string CTxTransportista { get; set; }
        public string CTxZona { get; set; }
        public string CTxReferencia { get; set; }
        public int NIdPuerto { get; set; }
        public short NIdBuque { get; set; }
        public int NIdHcTipoEmpaque { get; set; }
        public System.DateTime DFxEnvioCaja { get; set; }
        public System.DateTime DFxInspeccion { get; set; }
        public System.DateTime DFxInicial { get; set; }
        public System.DateTime DFxTermino { get; set; }
        public decimal NQnEnviada { get; set; }
        public decimal NQnRechazada { get; set; }
        public decimal NQnFacturada { get; set; }
        public decimal NQnPh { get; set; }
        public decimal NQnPesoPromedio { get; set; }
        public string CTxDefectosEmpaque { get; set; }
        public Nullable<decimal> NQnDefectosEmpaque { get; set; }
        public string CTxDefectosSeleccion { get; set; }
        public Nullable<decimal> NQnDefectosSeleccion { get; set; }
        public decimal NQnCalidad { get; set; }
        public string CTxSello { get; set; }
        public string CTxObservacion { get; set; }
        public string CCeCajaEnviada { get; set; }
        public System.DateTime DFxIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFxModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<short> NIdPuertoDestino { get; set; }
    
        public virtual TBLExBuque TBLExBuque { get; set; }
    }
}
