//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHcDetProduccion
    {
        public int NIdHcProduccion { get; set; }
        public short NNuSecuencia { get; set; }
        public string CCiProducto { get; set; }
        public decimal NQnProducida { get; set; }
        public decimal NQnRechazada { get; set; }
    
        public virtual TblHcCabProduccion TblHcCabProduccion { get; set; }
        public virtual TblIvProducto TblIvProducto { get; set; }
    }
}
