//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHcCabReqTransporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblHcCabReqTransporte()
        {
            this.TblHcDetReqTransporte = new HashSet<TblHcDetReqTransporte>();
            this.TblHcReqTransporteLugar = new HashSet<TblHcReqTransporteLugar>();
        }
    
        public int NIdHcReqTransporte { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public int NNuReqTransporte { get; set; }
        public string CciCliente { get; set; }
        public int NNuAnio { get; set; }
        public int NNuRequerimiento { get; set; }
        public System.DateTime DFxReqTransporte { get; set; }
        public int NIdHcPeriodo { get; set; }
        public string CTxProductoTransportar { get; set; }
        public int NIdCiaTransporte { get; set; }
        public string CCiTransportista { get; set; }
        public string CCiTipoVehiculo { get; set; }
        public string CTxPlaca { get; set; }
        public string CSnRentaChasis { get; set; }
        public Nullable<int> NNuDiaDiaRentaChasis { get; set; }
        public Nullable<int> NIdGeChasis { get; set; }
        public Nullable<int> NIdHcRuta { get; set; }
        public string CCiDocumentacion { get; set; }
        public string CNuContenedor { get; set; }
        public string CDsPropietarioContenedor { get; set; }
        public string CTxSello1 { get; set; }
        public string CTxSello2 { get; set; }
        public string CTxSello3 { get; set; }
        public string CSnGenerador { get; set; }
        public string CNuGenerador { get; set; }
        public string CDsProveedor { get; set; }
        public string CTxObservacion { get; set; }
        public string CCeReqTransporte { get; set; }
        public Nullable<int> NIdHcMedioMonitoreo { get; set; }
        public Nullable<System.DateTime> DHxHoraSalida { get; set; }
        public Nullable<System.DateTime> DHxHoraLLegada { get; set; }
        public Nullable<System.DateTime> DFxMonitoreo { get; set; }
        public string CDsUbicacionTransporte { get; set; }
        public string CDsNovedadMonitoreo { get; set; }
        public System.DateTime DFiIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFmModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public string CSnExcepcionMonitoreo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHcDetReqTransporte> TblHcDetReqTransporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHcReqTransporteLugar> TblHcReqTransporteLugar { get; set; }
    }
}
