//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIvAcumulaValor
    {
        public string CCiTipoMovimiento { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public int NNuControl { get; set; }
        public short NNuEntrega { get; set; }
        public string CCiProducto { get; set; }
        public short NNuSecuencia { get; set; }
        public int NNuMovimiento { get; set; }
        public string CCiBodega { get; set; }
        public string CCiUbicacion { get; set; }
        public System.DateTime DFxMovimiento { get; set; }
        public decimal NVtCantidadMvto { get; set; }
        public decimal NVrCostoPromedio { get; set; }
        public decimal NVtNuevoTotal { get; set; }
    }
}
