//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIvCabMvtoGeneralBatch
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public int NNuMovimientoBatch { get; set; }
        public string CCiSistemaOrigen { get; set; }
        public string CCiMotivo { get; set; }
        public Nullable<int> NNuMovimiento { get; set; }
        public System.DateTime DFxMovimiento { get; set; }
        public string CNuDcto { get; set; }
        public Nullable<decimal> NVtMontoTotal { get; set; }
        public string CDsReferencia { get; set; }
        public string CDsObservacion { get; set; }
        public string CCeMovimiento { get; set; }
        public string CCiDepartamento { get; set; }
        public string CCiEmpleadoSolicita { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFiIngreso { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DFmModifica { get; set; }
        public string CCiUsuarioAprueba { get; set; }
        public string CDsEstacionAprueba { get; set; }
        public Nullable<System.DateTime> DFxAprueba { get; set; }
        public string CCiProveedor { get; set; }
        public string CCiOrigen { get; set; }
        public Nullable<int> NNuControlMvtoContab { get; set; }
        public Nullable<int> NNuControlPeso { get; set; }
        public string CCiCiaNcNd { get; set; }
        public string CCiDivisionNcNd { get; set; }
        public string CCiSucursalNcNd { get; set; }
        public Nullable<int> NNuControlNcNd { get; set; }
        public string CNuSerieDcto { get; set; }
        public string CNuAutorizacionDcto { get; set; }
        public Nullable<int> NIdIvMvtoGeneral { get; set; }
        public string CSNPresupuesto { get; set; }
        public Nullable<int> NNuOrdenCompra { get; set; }
    }
}
