//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIvDetProductoPrecioDscto
    {
        public int NNuControl { get; set; }
        public int NNuSecuencia { get; set; }
        public Nullable<int> NNuDiasDesde { get; set; }
        public Nullable<int> NNuDiasHasta { get; set; }
        public Nullable<decimal> NQnPorcDscto { get; set; }
    
        public virtual TblIvCabProductoPrecioDscto TblIvCabProductoPrecioDscto { get; set; }
    }
}
