//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIvCabTomaFisica
    {
        public int NIdIvTomaSaldo { get; set; }
        public short NNuTomaFisica { get; set; }
        public short NNuHoja { get; set; }
        public int NIdIvMvtoGeneralIngreso { get; set; }
        public int NIdIvMvtoGeneralEgreso { get; set; }
        public string CCeTomaFisica { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFiIngreso { get; set; }
        public string CCiUsuarioReverso { get; set; }
        public string CDsEstacionReverso { get; set; }
        public Nullable<System.DateTime> DFiReverso { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DFiModifica { get; set; }
        public Nullable<int> NIdIvControlPeso { get; set; }
        public string CDsObservacion { get; set; }
    }
}
