//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIvSaldoCierre
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public short NNuAnio { get; set; }
        public int NNuPeriodo { get; set; }
        public string CCiBodega { get; set; }
        public string CCiUbicacion { get; set; }
        public string CCiProducto { get; set; }
        public string CCiUnidadMedida { get; set; }
        public decimal NQnExistencia { get; set; }
        public decimal NQnReserva { get; set; }
        public decimal NVrPromedio { get; set; }
        public decimal NVrMaximo { get; set; }
        public decimal NVrMinimo { get; set; }
        public decimal NVrTotal { get; set; }
        public Nullable<int> NNuRegistro { get; set; }
        public Nullable<decimal> NQnUnidad { get; set; }
    }
}
