//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLogMvtos
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CCiTipoComprobante { get; set; }
        public decimal NNuComprobante { get; set; }
        public decimal NnuSecuencial { get; set; }
        public Nullable<decimal> NNuAnio { get; set; }
        public Nullable<decimal> NNuMes { get; set; }
        public string CCiUsuario { get; set; }
        public Nullable<decimal> NNuTotDebitoDesp { get; set; }
        public Nullable<decimal> NNuTotCreditoDesp { get; set; }
        public string CCeDesp { get; set; }
        public Nullable<System.DateTime> DFxCambio { get; set; }
    }
}
