//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOcMotivoOrdenCompra
    {
        public string CCiMotivo { get; set; }
        public string CNoMotivo { get; set; }
        public string CCtMotivo { get; set; }
        public string CCeMotivo { get; set; }
    }
}
