//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOcDetOrdenCompra
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public decimal NNuOrdenCompra { get; set; }
        public decimal NNuSecuencia { get; set; }
        public string CCiBodega { get; set; }
        public string CCiProducto { get; set; }
        public string CNoProducto { get; set; }
        public string CCiUnidadMedida { get; set; }
        public Nullable<decimal> NQnOrdenada { get; set; }
        public Nullable<decimal> NQnDevuelta { get; set; }
        public Nullable<decimal> NQnRecibida { get; set; }
        public decimal NVtPrecioUnitario { get; set; }
        public decimal NVtMontoBruto { get; set; }
        public string CSNTieneDscto { get; set; }
        public Nullable<decimal> NVtPorcDscto1 { get; set; }
        public Nullable<decimal> NVtMontoDscto1 { get; set; }
        public Nullable<decimal> NVtPorcDscto2 { get; set; }
        public Nullable<decimal> NVtMontoDscto2 { get; set; }
        public Nullable<decimal> NVtPorcDscto3 { get; set; }
        public Nullable<decimal> NVtMontoDscto3 { get; set; }
        public decimal NVtPrecioSinIva { get; set; }
        public decimal NVtMontoSinIva { get; set; }
        public string CSNPagaIva { get; set; }
        public Nullable<decimal> NVtMontoIva { get; set; }
        public decimal NVtPrecioNeto { get; set; }
        public decimal NVtMontoItem { get; set; }
        public string CCiDpto { get; set; }
        public string CCiProyecto { get; set; }
        public string CCiSubProyecto { get; set; }
        public string CCiDepartamento { get; set; }
        public string CCiEmpleadoSolicita { get; set; }
        public string CDsObservacion { get; set; }
        public Nullable<decimal> NNuRequerimiento { get; set; }
        public string CDsReferencia { get; set; }
        public string CCiArea { get; set; }
        public string CCiTipoPres { get; set; }
        public decimal NVtPrecioAdicional { get; set; }
        public Nullable<decimal> NQnExistencia { get; set; }
        public string CSNActivoFijo { get; set; }
        public string CCeActivoFijo { get; set; }
        public string CCiActivoFijo { get; set; }
        public string CCiSubDpto { get; set; }
        public string CCiProductoCompra { get; set; }
        public Nullable<int> NIdPrPresupuesto { get; set; }
        public Nullable<decimal> NVtMontoAdicional { get; set; }
        public Nullable<decimal> NVtMontoSeguro { get; set; }
        public Nullable<decimal> NVtMontoCIF { get; set; }
        public Nullable<decimal> NVtCostoUnitarioCIF { get; set; }
        public Nullable<decimal> NNuPorcArancel { get; set; }
        public Nullable<decimal> NVtMontoArancel { get; set; }
        public Nullable<decimal> NVtMontoFDI { get; set; }
        public Nullable<decimal> NNuPorcICE { get; set; }
        public Nullable<decimal> NVtMontoICE { get; set; }
        public Nullable<decimal> NVtMontoOtrosGastos { get; set; }
        public Nullable<decimal> NVtCostoInventario { get; set; }
        public Nullable<decimal> NNuCostoUnitarioInventario { get; set; }
        public Nullable<int> NQnDiasConsumo { get; set; }
        public Nullable<decimal> NNuPorcFDI { get; set; }
        public Nullable<decimal> NNuPorcSobretasa { get; set; }
        public Nullable<decimal> NVtSobretasa { get; set; }
        public Nullable<decimal> NVtMontoBrutoExterno { get; set; }
        public Nullable<decimal> NVtTotalImportacion { get; set; }
        public string CNuLote { get; set; }
        public Nullable<System.DateTime> DFxVcmto { get; set; }
        public Nullable<decimal> NvtFactor { get; set; }
        public Nullable<decimal> NvtUltimoCostFOB { get; set; }
        public Nullable<decimal> NvtUltimoCostFactor { get; set; }
        public Nullable<decimal> NvtUltimoCostInventario { get; set; }
        public Nullable<decimal> NvtPorcUtilidad { get; set; }
        public Nullable<decimal> NVtPVP { get; set; }
        public Nullable<decimal> NVtPVPConIVA { get; set; }
        public Nullable<decimal> NQnCantidadFleteIMP { get; set; }
        public Nullable<decimal> NIdIvProductoSerie { get; set; }
        public string CCiModelo { get; set; }
        public string CCiUnidadPeso { get; set; }
        public Nullable<decimal> NQnPesoNetoUnitario { get; set; }
        public Nullable<decimal> NQnPesoNetoTotal { get; set; }
        public Nullable<decimal> NNuPorcISD { get; set; }
        public Nullable<decimal> NVtMontoISD { get; set; }
    }
}
