//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOcCabEntrega
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public decimal NNuOrdenCompra { get; set; }
        public short NNuEntrega { get; set; }
        public Nullable<int> NNuAnio { get; set; }
        public string CCiBodega { get; set; }
        public string CCiMotivo { get; set; }
        public decimal NNuMovimiento { get; set; }
        public System.DateTime DFxEntrega { get; set; }
        public decimal NVtBaseCero { get; set; }
        public decimal NVtBaseIva { get; set; }
        public decimal NVtPorcIva { get; set; }
        public decimal NVtMontoIva { get; set; }
        public decimal NVtMontoTotal { get; set; }
        public string CCeEntrega { get; set; }
        public string CDsReferencia { get; set; }
        public string CDsObservacion { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public System.DateTime DFiIngreso { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DFmModifica { get; set; }
        public string CNuSerieFact { get; set; }
        public string CNuSecuenciaFact { get; set; }
        public Nullable<int> NIdCiComprobante { get; set; }
        public string CSNPresupuesto { get; set; }
        public string CSNImportado { get; set; }
        public string CSNMigrado { get; set; }
        public Nullable<int> NIdIvControlPeso { get; set; }
        public string CNuSerieGuia { get; set; }
        public string CNuSecuenciaGuia { get; set; }
        public string CDsRecibidoPor { get; set; }
        public Nullable<int> NNuSecAlterna { get; set; }
        public Nullable<decimal> NVtImpuestoVerde { get; set; }
        public string CsnAutorizado { get; set; }
        public string CCiUsuarioAutoriza { get; set; }
        public string CDsEstacionAutoriza { get; set; }
        public Nullable<System.DateTime> DFxAutoriza { get; set; }
        public string CSnLeySolidaria { get; set; }
        public Nullable<decimal> NNuPorIVACompensacion { get; set; }
        public Nullable<decimal> NNuValIVACompensacion { get; set; }
        public Nullable<System.DateTime> DfxFechaReferenciaCRM { get; set; }
    }
}
