//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPrCabContrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPrCabContrato()
        {
            this.TblPrDetContrato = new HashSet<TblPrDetContrato>();
            this.TblPrDetContratoRubro = new HashSet<TblPrDetContratoRubro>();
        }
    
        public int NIdPrContrato { get; set; }
        public int NIdPrPresupuesto { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public int NNuContrato { get; set; }
        public Nullable<short> NNuAnio { get; set; }
        public Nullable<int> NNuSecAlterna { get; set; }
        public string CCiProveedor { get; set; }
        public decimal NVtContrato { get; set; }
        public Nullable<System.DateTime> DFxContrato { get; set; }
        public string CCeContrato { get; set; }
        public string CNoContrato { get; set; }
        public string CNoCargar { get; set; }
        public string CDsGlosaRubro { get; set; }
        public string CDsObservacion { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFiIngreso { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CdsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DfmModifica { get; set; }
        public string CciUsuarioAprueba { get; set; }
        public string CciEstacionAprueba { get; set; }
        public Nullable<System.DateTime> DFxAprueba { get; set; }
        public Nullable<decimal> NVtContratoaPagar { get; set; }
        public Nullable<decimal> NVtContratoaPagarxAnticipo { get; set; }
        public Nullable<decimal> NVtContratoaPagarxPermuta { get; set; }
        public Nullable<decimal> NVtContratoaPagarxAvanceObra { get; set; }
        public Nullable<decimal> NVtContratoPagado { get; set; }
        public Nullable<decimal> NVtContratoPagadoAnticipo { get; set; }
        public Nullable<decimal> NVtContratoPagadoPermuta { get; set; }
        public Nullable<decimal> NVtContratoPagadoAvanceObra { get; set; }
        public string CCtContratoRubro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPrDetContrato> TblPrDetContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPrDetContratoRubro> TblPrDetContratoRubro { get; set; }
    }
}
