//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPvBonoConsumo
    {
        public long NIdPvMovimiento { get; set; }
        public int NNuBono { get; set; }
        public string CciCliente { get; set; }
        public string CNoCliente { get; set; }
        public string CNuTelefono { get; set; }
        public string CDsDireccion { get; set; }
        public Nullable<System.DateTime> DFxBonoConsumo { get; set; }
        public Nullable<decimal> NVtBonoConsumo { get; set; }
    
        public virtual TblPvCabMovimiento TblPvCabMovimiento { get; set; }
    }
}
