//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPvPeriodo
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CCiPtoEmision { get; set; }
        public int NNuAnio { get; set; }
        public int NNuPeriodo { get; set; }
        public Nullable<System.DateTime> DFxPeriodoIni { get; set; }
        public Nullable<System.DateTime> DFxPeriodoFin { get; set; }
        public string CcePeriodo { get; set; }
        public Nullable<System.DateTime> DFxCierrePeriodo { get; set; }
        public string CCiUsuarioCierre { get; set; }
        public string CDsEstacionCierre { get; set; }
    }
}
