//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPrGrupoAnalisisPrecioUnitario
    {
        public int NIdPrPresupuesto { get; set; }
        public string CCiProyecto { get; set; }
        public string CCiSubProyecto { get; set; }
        public string CCiTipoInsumo { get; set; }
        public short NNuSecuencia { get; set; }
        public string CCiGrupoInsumo { get; set; }
        public string CCiUnidadMedida { get; set; }
        public Nullable<decimal> NQnUnitario { get; set; }
        public Nullable<decimal> NNuPrecioUnitario { get; set; }
        public Nullable<decimal> NQnRendimiento { get; set; }
        public decimal NVtCosto { get; set; }
        public string CCiModelo { get; set; }
    }
}
