//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrDetAnticipo
    {
        public int NIdPrAnticipo { get; set; }
        public int NNuSecuencia { get; set; }
        public int NNuSecContrato { get; set; }
        public decimal NNuPorcAnticipo { get; set; }
        public Nullable<decimal> NVtAnticipo { get; set; }
        public Nullable<System.DateTime> DFxAnticipo { get; set; }
        public string CDsObservacion { get; set; }
        public string CSnSeleccionado { get; set; }
    
        public virtual TblPrCabAnticipo TblPrCabAnticipo { get; set; }
    }
}
