//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPvTramitePtoEmision
    {
        public long NIdPvTramite { get; set; }
        public int NNuSecuencia { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CCiPtoEmision { get; set; }
        public string CNoPtoEmision { get; set; }
        public string CNuSerie { get; set; }
        public string CNuSecInicial { get; set; }
        public string CNuSecFinal { get; set; }
        public string CCiBodega { get; set; }
        public string CCiUbicacion { get; set; }
        public string CCeImprimeRetencion { get; set; }
        public string CCePtoEmision { get; set; }
        public string CCeInclusionPtoEmision { get; set; }
        public string CSnPtoEmisionAsignado { get; set; }
        public Nullable<System.DateTime> DFmModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<int> NIdPvTramiteAnterior { get; set; }
    }
}
