//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPrCabAnticipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPrCabAnticipo()
        {
            this.tblPrDetAnticipo = new HashSet<tblPrDetAnticipo>();
            this.TblPrDetAnticipoRubro = new HashSet<TblPrDetAnticipoRubro>();
        }
    
        public int NIdPrAnticipo { get; set; }
        public int NIdPrContrato { get; set; }
        public int NIdPrPresupuesto { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public int NNuContrato { get; set; }
        public int NNuAnticipo { get; set; }
        public int NNuAnio { get; set; }
        public Nullable<int> NNuSecAlterna { get; set; }
        public string CCtAnticipo { get; set; }
        public string CCiProveedor { get; set; }
        public decimal NVtTotalAnticipo { get; set; }
        public string CCeAnticipo { get; set; }
        public Nullable<System.DateTime> DFxAnticipo { get; set; }
        public string CDsObservacion { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFiIngreso { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DFmModifica { get; set; }
        public string CCiUsuarioAprueba { get; set; }
        public string CCiEstacionAprueba { get; set; }
        public Nullable<System.DateTime> DFxAprueba { get; set; }
        public string CCePlanilla { get; set; }
        public string CSnDetallaRubroAnticipo { get; set; }
        public Nullable<decimal> NVtSubtotalBruto { get; set; }
        public Nullable<decimal> NQnPorcFondoGarantia { get; set; }
        public Nullable<decimal> NVtFondoGarantia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPrDetAnticipo> tblPrDetAnticipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPrDetAnticipoRubro> TblPrDetAnticipoRubro { get; set; }
    }
}
