//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPrKardex
    {
        public int NIdPrKardex { get; set; }
        public short NNuSecuenciaOrigen { get; set; }
        public string CCtDctoOrigen { get; set; }
        public string CCiCiaOrigen { get; set; }
        public string CCiDivisionOrigen { get; set; }
        public string CCiSucursalOrigen { get; set; }
        public int NNuOrdenOrigen { get; set; }
        public short NNuEntregaOrigen { get; set; }
        public int NIdPrPresupuesto { get; set; }
        public System.DateTime DFxDctoOrigen { get; set; }
        public string CCiProyecto { get; set; }
        public string CCiSubProyecto { get; set; }
        public string CCiTipoInsumo { get; set; }
        public string CCiInsumo { get; set; }
        public string CCiUnidadMedida { get; set; }
        public Nullable<decimal> NQnConsumoPres { get; set; }
        public decimal NVtConsumoPres { get; set; }
        public Nullable<decimal> NQnNuevoSaldoPres { get; set; }
        public decimal NVtNuevoSaldoPres { get; set; }
        public Nullable<decimal> NQnConsumoContrato { get; set; }
        public decimal NVtConsumoContrato { get; set; }
        public Nullable<decimal> NQnNuevoSaldoContrato { get; set; }
        public decimal NVtNuevoSaldoContrato { get; set; }
        public string CCeKardex { get; set; }
        public Nullable<int> NIdPrContrato { get; set; }
    }
}
