//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPvCabTramite
    {
        public long NIdPvTramite { get; set; }
        public Nullable<System.DateTime> DFxTramite { get; set; }
        public string CCiCia { get; set; }
        public string CCiFormaEmision { get; set; }
        public string CCiTipoTramite { get; set; }
        public string CSnInicializaSecuencia { get; set; }
        public string CNuAutorizacionOrigen { get; set; }
        public Nullable<System.DateTime> DFxEmisionOrigen { get; set; }
        public Nullable<System.DateTime> DFxCaducidadOrigen { get; set; }
        public string CNuAutorizacion { get; set; }
        public Nullable<System.DateTime> DFxEmision { get; set; }
        public Nullable<System.DateTime> DFxCaducidad { get; set; }
        public string CTxObservacion { get; set; }
        public string CCeTramite { get; set; }
        public Nullable<System.DateTime> DFiIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DFmModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DFxAprueba { get; set; }
        public string CCiUsuarioAprueba { get; set; }
        public string CDsEstacionAprueba { get; set; }
    }
}
