//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPvBono
    {
        public int NIdPvActivacion { get; set; }
        public int NNuBono { get; set; }
        public string CnoDestinatario { get; set; }
        public string CsnCambiaProducto { get; set; }
        public string CnoProductoConsumir { get; set; }
        public Nullable<decimal> NVtBono { get; set; }
        public string CCeBono { get; set; }
        public string CsnImpreso { get; set; }
        public string CCeConsumoBono { get; set; }
        public Nullable<decimal> NvtTotalFacturado { get; set; }
        public System.DateTime DFxEmision { get; set; }
        public System.DateTime DfxCaducidad { get; set; }
        public System.DateTime DfiIngreso { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public string CDsEstacionIngreso { get; set; }
        public Nullable<System.DateTime> DfmModifica { get; set; }
        public string CCiUsuarioModifica { get; set; }
        public string CDsEstacionModifica { get; set; }
        public Nullable<System.DateTime> DfxAnula { get; set; }
        public string CCiUsuarioAnula { get; set; }
        public string CDsEstacionAnula { get; set; }
    
        public virtual TblPvCabActivacion TblPvCabActivacion { get; set; }
    }
}
