//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wrk3_AntTecRec
    {
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CCiTipoComprobante { get; set; }
        public decimal NnuComprobante { get; set; }
        public decimal NNuAnio { get; set; }
        public decimal NNuPeriodo { get; set; }
        public string CCiCuenta { get; set; }
        public string CCiTipoAuxiliar { get; set; }
        public string CCiAuxiliar { get; set; }
        public string cdsauxiliar { get; set; }
        public string ccitipodato { get; set; }
        public Nullable<decimal> NNuDebito { get; set; }
        public Nullable<decimal> NNuCredito { get; set; }
        public string cciusuario { get; set; }
    }
}
