//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wrk3_ComprobanteEgresoDcto
    {
        public short NNuRegistro { get; set; }
        public Nullable<short> NNuLineasMax { get; set; }
        public string CTxNumSerie { get; set; }
        public string CTxNumDocumento { get; set; }
        public Nullable<System.DateTime> DFmFechaFactura { get; set; }
        public string CDsReferencia { get; set; }
        public Nullable<decimal> NNuValorAbonado { get; set; }
    }
}
