//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrk_Impo_TblRetencion
    {
        public string CCiUsuarioEstacion { get; set; }
        public int NNuSecuenciaTabla { get; set; }
        public Nullable<int> NNuControl { get; set; }
        public Nullable<int> NNuFila { get; set; }
        public string CNuSerieFactura { get; set; }
        public string CNuSecuenciaFactura { get; set; }
        public string CNuSecuenciaRetencion { get; set; }
        public Nullable<decimal> NVtBaseRetFuente { get; set; }
        public Nullable<decimal> NNuValIVA { get; set; }
        public Nullable<decimal> NVtRetFte_1 { get; set; }
        public Nullable<decimal> NVtRetFte_2 { get; set; }
        public Nullable<decimal> NVtRetFte_5 { get; set; }
        public Nullable<decimal> NVtRetIVA_10 { get; set; }
        public Nullable<decimal> NVtRetIVA_20 { get; set; }
        public Nullable<decimal> NVtRetIVA_30 { get; set; }
        public Nullable<decimal> NVtRetIVA_50 { get; set; }
        public Nullable<decimal> NVtRetIVA_70 { get; set; }
        public Nullable<decimal> NVtRetIVA_100 { get; set; }
    }
}
