//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrk_Impo_vb6_vbnet
    {
        public string CCtProceso { get; set; }
        public string CCiUsuarioEstacion { get; set; }
        public string CCeProceso { get; set; }
    }
}
