//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wrk_TblGeValorCtbleInv
    {
        public string CCiBodega { get; set; }
        public string CCiUbicacion { get; set; }
        public string CCiClasificacion1 { get; set; }
        public string CCiClasificacion2 { get; set; }
        public string CCiClasificacion3 { get; set; }
        public string CCiMotivo { get; set; }
        public string CCtIngrEgr { get; set; }
        public string CciDpto { get; set; }
        public string CCiProyecto { get; set; }
        public string CCiSubProyecto { get; set; }
        public string CCiArea { get; set; }
        public decimal NNuValor { get; set; }
        public string CDsObservacion { get; set; }
        public Nullable<System.DateTime> DFxMovimiento { get; set; }
        public string CSnGrabaIva { get; set; }
        public Nullable<int> NNuMovimiento { get; set; }
        public Nullable<int> NIdIvMvtoGeneral { get; set; }
        public Nullable<short> NNuSecMvtoGeneral { get; set; }
        public string CCtMvto { get; set; }
        public string CDsReferencia { get; set; }
        public string CSNTransfAutomatica { get; set; }
        public string CNuControlUsuario { get; set; }
        public string CCiProducto { get; set; }
        public string CCeMovimiento { get; set; }
        public Nullable<int> NIdIvMovimientoOK { get; set; }
        public string CDsGlosaContrapartida { get; set; }
        public string CCiIdentificacionClien { get; set; }
    }
}
