//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrkCpDctoObraPagoManual
    {
        public string CCiUsuarioEstacion { get; set; }
        public string CCiParametro { get; set; }
        public int NNuSecDctoObraPagoManual { get; set; }
        public string CCiCiaPago { get; set; }
        public string CCiDivisionPago { get; set; }
        public string CCiSucursalPago { get; set; }
        public Nullable<short> NNuAnioPago { get; set; }
        public Nullable<int> NNuControlPago { get; set; }
        public Nullable<int> NNuSecuenciaPago { get; set; }
        public string CCtRegistro { get; set; }
        public string CCiDpto { get; set; }
        public Nullable<decimal> NVtMontoAplica { get; set; }
        public Nullable<decimal> NVtMontoAplicando { get; set; }
        public Nullable<decimal> NVtMontoPorAplicar { get; set; }
    }
}
