//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrkCpDetMvtoSaldoInicial
    {
        public string CCiUsuarioEstacion { get; set; }
        public int NNuSecuencia { get; set; }
        public string CCtTipoDoc { get; set; }
        public string CCiProveedor { get; set; }
        public Nullable<decimal> NNuValor { get; set; }
        public Nullable<System.DateTime> DFxDcto { get; set; }
        public Nullable<System.DateTime> DFmFechaRecepcion { get; set; }
        public Nullable<System.DateTime> DFmFechaVcto { get; set; }
        public Nullable<System.DateTime> FFxContabiliza { get; set; }
        public Nullable<System.DateTime> DFxFechaVigencia { get; set; }
        public string CDsReferencia { get; set; }
        public string CDsConcepto { get; set; }
        public string CCiPlanCta { get; set; }
        public string CCiCuenta { get; set; }
        public string CCiTipoAuxiliar { get; set; }
        public string CCiAuxiliar { get; set; }
        public string CSnAceptaAuxiliar { get; set; }
        public string CDsNovedad { get; set; }
        public string CCeItem { get; set; }
        public string CciIdentificacion { get; set; }
    }
}
