//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrkFaDetImportaFacturaElectronica
    {
        public string CCiUsuarioEstacion { get; set; }
        public int NNuFila { get; set; }
        public int NNuSecRegistro { get; set; }
        public string codigoPrincipal { get; set; }
        public string codigoAuxiliar { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> precioUnitario { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> precioTotalSinImpuesto { get; set; }
        public string CSnGrabaIva { get; set; }
    }
}
