//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPANACEAPROD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int id { get; set; }
        public string number { get; set; }
        public int sequential { get; set; }
        public System.DateTime emissionDate { get; set; }
        public Nullable<System.DateTime> authorizationDate { get; set; }
        public string authorizationNumber { get; set; }
        public string accessKey { get; set; }
        public string description { get; set; }
        public string reference { get; set; }
        public int id_emissionPoint { get; set; }
        public int id_documentType { get; set; }
        public int id_documentState { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public Nullable<bool> isOpen { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual DocumentState DocumentState { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
