//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrigenListaLP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public int id_customerType { get; set; }
        public string name_customerType { get; set; }
        public bool forceToKeepAccountsCusm { get; set; }
        public bool specialTaxPayerCusm { get; set; }
        public Nullable<int> id_vendorAssigned { get; set; }
        public string name_vendorAssigned { get; set; }
        public Nullable<int> id_economicGroupCusm { get; set; }
        public string name_economicGroup { get; set; }
        public bool isActive { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public bool applyIva { get; set; }
    
        public virtual CustomerType CustomerType { get; set; }
        public virtual EconomicGroup EconomicGroup { get; set; }
        public virtual Person Person { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
