//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrigenListaLP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Document1 = new HashSet<Document>();
            this.DocumentStateChange = new HashSet<DocumentStateChange>();
            this.Notification = new HashSet<Notification>();
        }
    
        public int id { get; set; }
        public string number { get; set; }
        public int sequential { get; set; }
        public System.DateTime emissionDate { get; set; }
        public Nullable<System.DateTime> authorizationDate { get; set; }
        public string authorizationNumber { get; set; }
        public string accessKey { get; set; }
        public string description { get; set; }
        public string reference { get; set; }
        public int id_emissionPoint { get; set; }
        public int id_documentType { get; set; }
        public int id_documentState { get; set; }
        public Nullable<int> id_BaseDocument { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual EmissionPoint EmissionPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Document1 { get; set; }
        public virtual Document Document2 { get; set; }
        public virtual DocumentState DocumentState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentStateChange> DocumentStateChange { get; set; }
        public virtual DrainingTest DrainingTest { get; set; }
        public virtual LiquidationMaterialSupplies LiquidationMaterialSupplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notification { get; set; }
        public virtual PriceList PriceList { get; set; }
    }
}
