//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrigenListaLP
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailConfiguration
    {
        public int id { get; set; }
        public string host { get; set; }
        public string mail { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public int port { get; set; }
        public bool enableSsl { get; set; }
        public bool isActive { get; set; }
    }
}
