using System;

namespace BibliotecaReporte.Model.FacturasExterior
{
    internal class FacturaElectronicaModel
    {
        public int ID { get; set; }
       
        public int Id_saleOrder { get; set; }
        public int Id_buyer { get; set; }
        public int Id_remissionGuide { get; set; }
        public decimal Subtotal12 { get; set; }
        public decimal SubTotal0 { get; set; }
        public decimal SubTotalNoObjectIVA { get; set; }
        public decimal SubTotalExentIVA { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Descuento { get; set; }
        public decimal ValueICE { get; set; }
        public decimal ValueIRBPNR { get; set; }
        public decimal IVA { get; set; }
        public decimal Tip { get; set; }
        public decimal TotalValue { get; set; }
        public decimal SubTotalSinImpuesto { get; set; }
        public int Id_InvoiceType { get; set; }
        public int Id_InvoiceMode { get; set; }
        public int InvoiceDetail_id { get; set; }
        public int Id_invoice { get; set; }
        public int Id_item { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public decimal Precio { get; set; }
        public decimal Dscto { get; set; }
        public decimal TotalPriceWithoutTax { get; set; }
        public decimal Iva { get; set; }
        public decimal Iva0 { get; set; }
        public decimal IvaNoObject { get; set; }
        public decimal IvaExented { get; set; }
        public decimal InvoiceDetail_valueICE { get; set; }
        public decimal InvoiceDetail_valueIRBPNR { get; set; }
        public decimal PrecioTotal { get; set; }
        public string DescriptionAuxCode { get; set; }
        public string MasterCode { get; set; }
        public int Cartones { get; set; }
        public int Id_metricUnit { get; set; }
        public int Id_metricUnitInvoiceDetail { get; set; }
        public decimal Cantidad { get; set; }
        public DateTime DateUpdate { get; set; }
        public string CodePresentation { get; set; }
        public decimal PresentationMinimum { get; set; }
        public decimal PresentationMaximum { get; set; }
        public int InvoiceExterior_id { get; set; }
        public int Id_productionOrder { get; set; }
        public int Id_releaseProduction { get; set; }
        public int Id_termsNegotiation { get; set; }
        public int Id_PaymentMethod { get; set; }
        public int Id_PaymentTerm { get; set; }
        public int Id_portShipment { get; set; }
        public int Id_portDestination { get; set; }
        public int Id_portDischarge { get; set; }
        public DateTime FechaEmbarque { get; set; }
        public int Id_shippingAgency { get; set; }
        public string DAE { get; set; }
        public string BL { get; set; }
        public string GuiaRemision { get; set; }
        public string Buque2 { get; set; }
        public string Buque { get; set; }
        public string VIAJE { get; set; }
        public int TotalCM { get; set; }
        public int Id_capacityContainer { get; set; }
        public int Id_tariffHeading { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public string PtoEmision { get; set; }
        public string Establecimiento { get; set; }
        public int Secuencial { get; set; }
        public decimal ValorTotalFob { get; set; }
        public decimal FleteInternacional { get; set; }
        public decimal SeguroInternacional { get; set; }
        public decimal GastosAduaneros { get; set; }
        public decimal GastosTrasnporte { get; set; }
        public int Id_metricUnitInvoice { get; set; }
        public int InvoiceExterior_id_userCreate { get; set; }
        public DateTime InvoiceExterior_dateCreate { get; set; }
        public int InvoiceExterior_id_userUpdate { get; set; }
        public DateTime InvoiceExterior_dateUpdate { get; set; }
        public int Id_consignee { get; set; }
        public int Id_notifier { get; set; }
        public string PurchaseOrder { get; set; }
        public int Id_ShippingLine { get; set; }
        public string Unidad { get; set; }
        public string RazonSocial { get; set; }
        public string RucCedula { get; set; }
        public string CodigoAuxiliar { get; set; }
        public string CodigoPrincipal { get; set; }
        public string Descripcion { get; set; }
        public string PuertoDescarga { get; set; }
        public string TipoPuertoDescarga { get; set; }
        public string PuertoDeEmbaruqe { get; set; }
        public string TipoPuertoEmbarque { get; set; }
        public string PuertoDestino { get; set; }
        public string TipoPuertoDestino { get; set; }
        public string EmissionPoint_name { get; set; }
        public string BusinessName { get; set; }
        public string DirMatiz { get; set; }
        public string Factura { get; set; }
        public DateTime FEchaEmision { get; set; }
        public string NumeroAutorizacion { get; set; }
        public DateTime FechaHoraAutorizacion { get; set; }
        public decimal Pesonetokilos { get; set; }
        public decimal Pesonetolibras { get; set; }
        public decimal Pesobrutokilos { get; set; }
        public decimal Pesobrutolibras { get; set; }
        public decimal Pesoglaskilos { get; set; }
        public decimal Pesoglaslibras { get; set; }
        public string FormaDePago { get; set; }
        public string Plazo { get; set; }
        public string Tiempo { get; set; }
        public string PaisDestino { get; set; }
        public string Naviera { get; set; }
        public string Linea_Naviera { get; set; }
        public string Partida { get; set; }
        public string Partida2 { get; set; }
        public string DirSucural { get; set; }
        public string Division_Address { get; set; }
        public string RUCcia { get; set; }
        public string NombreCia { get; set; }
        public string Archivo { get; set; }
        public string ClaveAcceso { get; set; }
        public string TerminoNegocia { get; set; }
        public string ContribuyenteEspecialNo { get; set; }
        public string Ambiente { get; set; }
        public string Emision { get; set; }
        public string ObligadoLlevarContabilidad { get; set; }
        public string CodigoEstado { get; set; }
        public string TerminoNegociacion { get; set; }
        public int NumeroContenedores { get; set; }
        public string Proforma { get; set; }
        public string Orden { get; set; }
        public string RUCEXTERIOR { get; set; }

        public string NoConten { get; set; }

        public decimal Valor { get; set; }
    }
}