//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversionItemPurchasePlanning
    {
        public int id { get; set; }
        public Nullable<int> id_itemPurchasePlanning { get; set; }
        public int id_itemTypeCategoryPurchasePlanning { get; set; }
        public decimal quantityPurchasePlanning { get; set; }
        public int id_itemNeeded { get; set; }
        public decimal quantityNeeded { get; set; }
        public int id_company { get; set; }
        public bool isActive { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual ItemTypeCategory ItemTypeCategory { get; set; }
    }
}
