//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrainingTestDetail
    {
        public int id { get; set; }
        public Nullable<int> idDrainingTest { get; set; }
        public int order { get; set; }
        public decimal quantity { get; set; }
        public int idMetricUnit { get; set; }
        public Nullable<int> idDrainingTestSampling { get; set; }
    
        public virtual DrainingTestSampling DrainingTestSampling { get; set; }
        public virtual MetricUnit MetricUnit { get; set; }
    }
}
