//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceExteriorWeightDivided
    {
        public int id { get; set; }
        public int id_InvoiceExteriorDivided { get; set; }
        public int id_WeightType { get; set; }
        public int id_metricUnit { get; set; }
        public Nullable<decimal> peso { get; set; }
    
        public virtual InvoiceExteriorDivided InvoiceExteriorDivided { get; set; }
    }
}
