//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidationFreightDetail
    {
        public int id { get; set; }
        public int id_LiquidationFreight { get; set; }
        public int id_remisionGuide { get; set; }
        public decimal price { get; set; }
        public decimal pricedays { get; set; }
        public decimal priceextension { get; set; }
        public decimal priceadjustment { get; set; }
        public decimal pricetotal { get; set; }
        public decimal pricesubtotal { get; set; }
        public decimal pricesavance { get; set; }
        public bool isActive { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public Nullable<decimal> PriceCancelled { get; set; }
        public string descriptionRG { get; set; }
        public Nullable<int> idOwnerVehicle { get; set; }
    
        public virtual LiquidationFreight LiquidationFreight { get; set; }
        public virtual Person Person { get; set; }
        public virtual RemissionGuide RemissionGuide { get; set; }
    }
}
