//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidationTurn
    {
        public int id { get; set; }
        public System.DateTime emissionDate { get; set; }
        public int id_turn { get; set; }
        public int id_personProcessPlant { get; set; }
        public int id_userCreate { get; set; }
        public int id_userUpdate { get; set; }
        public Nullable<System.DateTime> liquidationDate { get; set; }
        public Nullable<System.TimeSpan> liquidationTime { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Person Person { get; set; }
        public virtual Turn Turn { get; set; }
    }
}
