//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidationCartOnCartDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LiquidationCartOnCartDetail()
        {
            this.InventoryMovePlantTransferDetail = new HashSet<InventoryMovePlantTransferDetail>();
        }
    
        public int id { get; set; }
        public int id_LiquidationCartOnCart { get; set; }
        public Nullable<int> id_SalesOrder { get; set; }
        public Nullable<int> id_SalesOrderDetail { get; set; }
        public Nullable<int> id_ProductionCart { get; set; }
        public int id_ItemLiquidation { get; set; }
        public decimal quatityBoxesIL { get; set; }
        public decimal quantityKgsIL { get; set; }
        public decimal quantityPoundsIL { get; set; }
        public int id_ItemToWarehouse { get; set; }
        public decimal quantityKgsITW { get; set; }
        public decimal quantityPoundsITW { get; set; }
        public Nullable<int> id_Client { get; set; }
        public Nullable<decimal> boxesReceived { get; set; }
        public Nullable<int> id_subProcessIOProductionProcess { get; set; }
        public string observation { get; set; }
        public Nullable<int> id_ProductionLotManual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMovePlantTransferDetail> InventoryMovePlantTransferDetail { get; set; }
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual LiquidationCartOnCart LiquidationCartOnCart { get; set; }
        public virtual Person Person { get; set; }
        public virtual ProductionCart ProductionCart { get; set; }
        public virtual ProductionLot ProductionLot { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual SalesOrderDetail SalesOrderDetail { get; set; }
        public virtual SubProcessIOProductionProcess SubProcessIOProductionProcess { get; set; }
    }
}
