//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lot()
        {
            this.AdvanceProvider = new HashSet<AdvanceProvider>();
            this.AutomaticTransferDetail = new HashSet<AutomaticTransferDetail>();
            this.InventoryMoveDetail = new HashSet<InventoryMoveDetail>();
            this.MasteredDetail = new HashSet<MasteredDetail>();
            this.MasteredDetail1 = new HashSet<MasteredDetail>();
            this.OpeningClosingPlateLyingDetail = new HashSet<OpeningClosingPlateLyingDetail>();
            this.ProductionCostsProcessDetail = new HashSet<ProductionCostsProcessDetail>();
            this.QualityControl = new HashSet<QualityControl>();
        }
    
        public int id { get; set; }
        public string number { get; set; }
        public int id_company { get; set; }
        public bool hasAdvanceProvider { get; set; }
        public string internalNumber { get; set; }
        public bool isClosed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvanceProvider> AdvanceProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutomaticTransferDetail> AutomaticTransferDetail { get; set; }
        public virtual Document Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMoveDetail> InventoryMoveDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasteredDetail> MasteredDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasteredDetail> MasteredDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpeningClosingPlateLyingDetail> OpeningClosingPlateLyingDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionCostsProcessDetail> ProductionCostsProcessDetail { get; set; }
        public virtual ProductionLot ProductionLot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityControl> QualityControl { get; set; }
    }
}
