//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.AccountingTemplate = new HashSet<AccountingTemplate>();
            this.BusinessOportunity = new HashSet<BusinessOportunity>();
            this.BusinessOportunity1 = new HashSet<BusinessOportunity>();
            this.BusinessOportunityCompetition = new HashSet<BusinessOportunityCompetition>();
            this.BusinessOportunityPartner = new HashSet<BusinessOportunityPartner>();
            this.BusinessOportunityPlanningDetail = new HashSet<BusinessOportunityPlanningDetail>();
            this.CopackingTariff = new HashSet<CopackingTariff>();
            this.Customer1 = new HashSet<Customer>();
            this.Customer2 = new HashSet<Customer>();
            this.DriverVeicleProviderTransport = new HashSet<DriverVeicleProviderTransport>();
            this.ForeignCustomerIdentification = new HashSet<ForeignCustomerIdentification>();
            this.FrameworkContract = new HashSet<FrameworkContract>();
            this.GroupPersonByRolDetail = new HashSet<GroupPersonByRolDetail>();
            this.Headless = new HashSet<Headless>();
            this.Headless1 = new HashSet<Headless>();
            this.HistoryMigrationPerson = new HashSet<HistoryMigrationPerson>();
            this.InventoryMove = new HashSet<InventoryMove>();
            this.InventoryMove1 = new HashSet<InventoryMove>();
            this.InventoryMove2 = new HashSet<InventoryMove>();
            this.Invoice = new HashSet<Invoice>();
            this.Invoice1 = new HashSet<Invoice>();
            this.InvoiceCommercial = new HashSet<InvoiceCommercial>();
            this.InvoiceCommercial1 = new HashSet<InvoiceCommercial>();
            this.InvoiceExterior = new HashSet<InvoiceExterior>();
            this.InvoiceExterior1 = new HashSet<InvoiceExterior>();
            this.InvoiceExterior2 = new HashSet<InvoiceExterior>();
            this.InvoiceExterior3 = new HashSet<InvoiceExterior>();
            this.ItemGeneral = new HashSet<ItemGeneral>();
            this.ItemIngredient = new HashSet<ItemIngredient>();
            this.LiquidationCartOnCart = new HashSet<LiquidationCartOnCart>();
            this.LiquidationCartOnCartDetail = new HashSet<LiquidationCartOnCartDetail>();
            this.LiquidationFreight = new HashSet<LiquidationFreight>();
            this.LiquidationFreightDetail = new HashSet<LiquidationFreightDetail>();
            this.LiquidationFreightRiver = new HashSet<LiquidationFreightRiver>();
            this.LiquidationFreightRiverDetail = new HashSet<LiquidationFreightRiverDetail>();
            this.LiquidationTurn = new HashSet<LiquidationTurn>();
            this.MachineForProd = new HashSet<MachineForProd>();
            this.MachineProdOpeningDetail = new HashSet<MachineProdOpeningDetail>();
            this.Mastered = new HashSet<Mastered>();
            this.MigrationPerson = new HashSet<MigrationPerson>();
            this.PurchaseOrder = new HashSet<PurchaseOrder>();
            this.Vehicle = new HashSet<Vehicle>();
            this.PersonGroupRol = new HashSet<PersonGroupRol>();
            this.PriceListPersonPersonRol = new HashSet<PriceListPersonPersonRol>();
            this.ProductionCostsBuys = new HashSet<ProductionCostsBuys>();
            this.ProductionLot = new HashSet<ProductionLot>();
            this.ProductionLot1 = new HashSet<ProductionLot>();
            this.PurchaseOrder1 = new HashSet<PurchaseOrder>();
            this.PurchaseOrder2 = new HashSet<PurchaseOrder>();
            this.PurchasePlanningDetail = new HashSet<PurchasePlanningDetail>();
            this.RemissionGuide = new HashSet<RemissionGuide>();
            this.RemissionGuideAssignedStaff = new HashSet<RemissionGuideAssignedStaff>();
            this.RemissionGuideRiverAssignedStaff = new HashSet<RemissionGuideRiverAssignedStaff>();
            this.RemissionGuide1 = new HashSet<RemissionGuide>();
            this.RemissionGuide2 = new HashSet<RemissionGuide>();
            this.RemissionGuideReportLinealDataHelp = new HashSet<RemissionGuideReportLinealDataHelp>();
            this.RemissionGuideReportLinealDataHelp1 = new HashSet<RemissionGuideReportLinealDataHelp>();
            this.RemissionGuideRiver = new HashSet<RemissionGuideRiver>();
            this.RemissionGuideRiver1 = new HashSet<RemissionGuideRiver>();
            this.RemissionGuideRiverReportLinealDataHelp = new HashSet<RemissionGuideRiverReportLinealDataHelp>();
            this.RemissionGuideRiverReportLinealDataHelp1 = new HashSet<RemissionGuideRiverReportLinealDataHelp>();
            this.RemissionGuideRiverTransportation = new HashSet<RemissionGuideRiverTransportation>();
            this.RemissionGuideTransportation = new HashSet<RemissionGuideTransportation>();
            this.RemissionGuideTransportation1 = new HashSet<RemissionGuideTransportation>();
            this.RemissionGuideTransportation2 = new HashSet<RemissionGuideTransportation>();
            this.RequestInventoryMove = new HashSet<RequestInventoryMove>();
            this.RequestInventoryMove1 = new HashSet<RequestInventoryMove>();
            this.RequestInventoryMove2 = new HashSet<RequestInventoryMove>();
            this.SalesOrder = new HashSet<SalesOrder>();
            this.SalesQuotationExterior = new HashSet<SalesQuotationExterior>();
            this.SalesQuotationExterior1 = new HashSet<SalesQuotationExterior>();
            this.SalesQuotationExterior2 = new HashSet<SalesQuotationExterior>();
            this.SalesQuotationExterior3 = new HashSet<SalesQuotationExterior>();
            this.SalesQuotationExterior4 = new HashSet<SalesQuotationExterior>();
            this.ProductionScheduleScheduleDetail = new HashSet<ProductionScheduleScheduleDetail>();
            this.VehicleProviderTransportBilling = new HashSet<VehicleProviderTransportBilling>();
            this.VeicleProviderTransport = new HashSet<VeicleProviderTransport>();
            this.WarehouseLocation = new HashSet<WarehouseLocation>();
            this.Rol = new HashSet<Rol>();
            this.ProductionLot11 = new HashSet<ProductionLot>();
            this.SalesOrder1 = new HashSet<SalesOrder>();
            this.ProductionCostAllocationPeriodDetails = new HashSet<ProductionCostAllocationPeriodDetail>();
            this.ProductionCostCoefficientExecutionDetails = new HashSet<ProductionCostCoefficientExecutionDetail>();
            this.ProductionCostCoefficientExecutionPlants = new HashSet<ProductionCostCoefficientExecutionPlant>();
            this.InventoryMoveDetail = new HashSet<InventoryMoveDetail>();
            this.ProductionCostCoefficient = new HashSet<ProductionCostCoefficient>();
            this.AutomaticTransfer = new HashSet<AutomaticTransfer>();
            this.AutomaticTransfer1 = new HashSet<AutomaticTransfer>();
        }
    
        public int id { get; set; }
        public int id_personType { get; set; }
        public int id_identificationType { get; set; }
        public string identification_number { get; set; }
        public string fullname_businessName { get; set; }
        public byte[] photo { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public Nullable<int> id_company { get; set; }
        public bool isActive { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public string codeCI { get; set; }
        public string bCC { get; set; }
        public string tradeName { get; set; }
        public string cellPhoneNumberPerson { get; set; }
        public string emailCC { get; set; }
        public string processPlant { get; set; }
        public byte[] firm { get; set; }
        public Nullable<bool> isCopacking { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingTemplate> AccountingTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessOportunity> BusinessOportunity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessOportunity> BusinessOportunity1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessOportunityCompetition> BusinessOportunityCompetition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessOportunityPartner> BusinessOportunityPartner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessOportunityPlanningDetail> BusinessOportunityPlanningDetail { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CopackingTariff> CopackingTariff { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customer2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverVeicleProviderTransport> DriverVeicleProviderTransport { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ForeignCustomer ForeignCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForeignCustomerIdentification> ForeignCustomerIdentification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrameworkContract> FrameworkContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupPersonByRolDetail> GroupPersonByRolDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Headless> Headless { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Headless> Headless1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryMigrationPerson> HistoryMigrationPerson { get; set; }
        public virtual IdentificationType IdentificationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMove> InventoryMove { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMove> InventoryMove1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMove> InventoryMove2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceCommercial> InvoiceCommercial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceCommercial> InvoiceCommercial1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceExterior> InvoiceExterior { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceExterior> InvoiceExterior1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceExterior> InvoiceExterior2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceExterior> InvoiceExterior3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemGeneral> ItemGeneral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemIngredient> ItemIngredient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiquidationCartOnCart> LiquidationCartOnCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiquidationCartOnCartDetail> LiquidationCartOnCartDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiquidationFreight> LiquidationFreight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiquidationFreightDetail> LiquidationFreightDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiquidationFreightRiver> LiquidationFreightRiver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiquidationFreightRiverDetail> LiquidationFreightRiverDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiquidationTurn> LiquidationTurn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineForProd> MachineForProd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineProdOpeningDetail> MachineProdOpeningDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mastered> Mastered { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MigrationPerson> MigrationPerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicle { get; set; }
        public virtual PersonType PersonType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonGroupRol> PersonGroupRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceListPersonPersonRol> PriceListPersonPersonRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionCostsBuys> ProductionCostsBuys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionLot> ProductionLot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionLot> ProductionLot1 { get; set; }
        public virtual Provider Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrder2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasePlanningDetail> PurchasePlanningDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuide> RemissionGuide { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideAssignedStaff> RemissionGuideAssignedStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideRiverAssignedStaff> RemissionGuideRiverAssignedStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuide> RemissionGuide1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuide> RemissionGuide2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideReportLinealDataHelp> RemissionGuideReportLinealDataHelp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideReportLinealDataHelp> RemissionGuideReportLinealDataHelp1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideRiver> RemissionGuideRiver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideRiver> RemissionGuideRiver1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideRiverReportLinealDataHelp> RemissionGuideRiverReportLinealDataHelp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideRiverReportLinealDataHelp> RemissionGuideRiverReportLinealDataHelp1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideRiverTransportation> RemissionGuideRiverTransportation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideTransportation> RemissionGuideTransportation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideTransportation> RemissionGuideTransportation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideTransportation> RemissionGuideTransportation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestInventoryMove> RequestInventoryMove { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestInventoryMove> RequestInventoryMove1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestInventoryMove> RequestInventoryMove2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrder> SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesQuotationExterior> SalesQuotationExterior { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesQuotationExterior> SalesQuotationExterior1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesQuotationExterior> SalesQuotationExterior2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesQuotationExterior> SalesQuotationExterior3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesQuotationExterior> SalesQuotationExterior4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionScheduleScheduleDetail> ProductionScheduleScheduleDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleProviderTransportBilling> VehicleProviderTransportBilling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeicleProviderTransport> VeicleProviderTransport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseLocation> WarehouseLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rol> Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionLot> ProductionLot11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrder> SalesOrder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionCostAllocationPeriodDetail> ProductionCostAllocationPeriodDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionCostCoefficientExecutionDetail> ProductionCostCoefficientExecutionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionCostCoefficientExecutionPlant> ProductionCostCoefficientExecutionPlants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMoveDetail> InventoryMoveDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionCostCoefficient> ProductionCostCoefficient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutomaticTransfer> AutomaticTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutomaticTransfer> AutomaticTransfer1 { get; set; }
    }
}
