//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceListItemSizeDetail
    {
        public int Id { get; set; }
        public int Id_PriceList { get; set; }
        public int Id_Itemsize { get; set; }
        public decimal price { get; set; }
        public decimal commission { get; set; }
        public int id_classShrimp { get; set; }
        public int id_class { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ClassShrimp ClassShrimp { get; set; }
        public virtual ItemSize ItemSize { get; set; }
        public virtual PriceList PriceList { get; set; }
    }
}
