//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionLotPaymentDistributed
    {
        public int id { get; set; }
        public int id_productionLotPayment { get; set; }
        public int id_item { get; set; }
        public Nullable<int> number_box { get; set; }
        public decimal pound { get; set; }
        public Nullable<decimal> kilogram { get; set; }
        public Nullable<decimal> performance { get; set; }
        public decimal priceLP { get; set; }
        public decimal totalPayLP { get; set; }
        public bool isActive { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ProductionLotPayment ProductionLotPayment { get; set; }
    }
}
