//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionSchedule()
        {
            this.InventoryReservation = new HashSet<InventoryReservation>();
            this.ProductionScheduleInventoryReservationDetail = new HashSet<ProductionScheduleInventoryReservationDetail>();
            this.ProductionScheduleProductionOrderDetail = new HashSet<ProductionScheduleProductionOrderDetail>();
            this.ProductionScheduleProductionOrderDetailSalesOrderDetail = new HashSet<ProductionScheduleProductionOrderDetailSalesOrderDetail>();
            this.ProductionScheduleScheduleDetailPurchaseRequestDetail = new HashSet<ProductionScheduleScheduleDetailPurchaseRequestDetail>();
            this.ProductionSchedulePurchaseRequestDetail = new HashSet<ProductionSchedulePurchaseRequestDetail>();
            this.ProductionScheduleRequestDetail = new HashSet<ProductionScheduleRequestDetail>();
            this.ProductionScheduleScheduleDetail = new HashSet<ProductionScheduleScheduleDetail>();
        }
    
        public int id { get; set; }
        public int id_productionSchedulePeriod { get; set; }
        public int id_personSchedule { get; set; }
        public int id_company { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryReservation> InventoryReservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionScheduleInventoryReservationDetail> ProductionScheduleInventoryReservationDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionScheduleProductionOrderDetail> ProductionScheduleProductionOrderDetail { get; set; }
        public virtual ProductionSchedulePeriod ProductionSchedulePeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionScheduleProductionOrderDetailSalesOrderDetail> ProductionScheduleProductionOrderDetailSalesOrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionScheduleScheduleDetailPurchaseRequestDetail> ProductionScheduleScheduleDetailPurchaseRequestDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionSchedulePurchaseRequestDetail> ProductionSchedulePurchaseRequestDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionScheduleRequestDetail> ProductionScheduleRequestDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionScheduleScheduleDetail> ProductionScheduleScheduleDetail { get; set; }
    }
}
