//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepoKardexCostoResumenModel
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> cantidadesUnidades { get; set; }
        public Nullable<decimal> promedioUnidades { get; set; }
        public Nullable<decimal> cantidadesLibras { get; set; }
        public Nullable<decimal> promedioLibras { get; set; }
        public Nullable<decimal> costoTotal { get; set; }
    }
}
