//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesQuotationExterior
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesQuotationExterior()
        {
            this.SalesOrderDetailSalesQuotationExterior = new HashSet<SalesOrderDetailSalesQuotationExterior>();
            this.SalesQuotationExteriorDocument = new HashSet<SalesQuotationExteriorDocument>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_termsNegotiation { get; set; }
        public Nullable<int> id_PaymentMethod { get; set; }
        public Nullable<int> id_PaymentTerm { get; set; }
        public Nullable<int> id_portDestination { get; set; }
        public Nullable<int> id_portDischarge { get; set; }
        public string purchaseOrder { get; set; }
        public Nullable<System.DateTime> dateShipment { get; set; }
        public string direccion { get; set; }
        public string email { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public Nullable<int> id_consignee { get; set; }
        public Nullable<int> id_notifier { get; set; }
        public Nullable<int> idVendor { get; set; }
        public Nullable<int> id_metricUnitInvoice { get; set; }
        public int totalBoxes { get; set; }
        public Nullable<int> usedBoxes { get; set; }
        public Nullable<int> pendingBoxes { get; set; }
        public Nullable<int> numBoxesPlusMinus { get; set; }
        public decimal valueTotalFOB { get; set; }
        public decimal valueInternationalFreight { get; set; }
        public decimal valueInternationalInsurance { get; set; }
        public decimal valueCustomsExpenditures { get; set; }
        public decimal valueTransportationExpenses { get; set; }
        public decimal valuetotalCIF { get; set; }
        public Nullable<int> id_bank { get; set; }
        public Nullable<int> id_personContact { get; set; }
        public Nullable<int> id_portShipment { get; set; }
        public string Product { get; set; }
        public string ColourGrade { get; set; }
        public string PackingDetails { get; set; }
        public string ContainerDetails { get; set; }
        public Nullable<decimal> valueSubscribed { get; set; }
        public Nullable<int> numeroContenedores { get; set; }
        public Nullable<int> id_capacityContainer { get; set; }
        public Nullable<int> temperatureInstruction { get; set; }
        public Nullable<int> idTipoTemperatura { get; set; }
        public Nullable<System.DateTime> temperatureInstrucDate { get; set; }
        public Nullable<int> id_personContactConsignatario { get; set; }
        public string vessel { get; set; }
        public string trip { get; set; }
        public string strDateShipment { get; set; }
        public string transport { get; set; }
        public int id_addressCustomer { get; set; }
        public Nullable<int> id_portTerminal { get; set; }
        public string Shipment_date { get; set; }
        public Nullable<int> id_BankTransfer { get; set; }
        public string noContrato { get; set; }
        public string PO { get; set; }
    
        public virtual BoxCardAndBank BoxCardAndBank { get; set; }
        public virtual CapacityContainer CapacityContainer { get; set; }
        public virtual ForeignCustomerIdentification ForeignCustomerIdentification { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual MetricUnit MetricUnit { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual PaymentTerm PaymentTerm { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Person Person2 { get; set; }
        public virtual Person Person3 { get; set; }
        public virtual Person Person4 { get; set; }
        public virtual Port Port { get; set; }
        public virtual Port Port1 { get; set; }
        public virtual Port Port2 { get; set; }
        public virtual Port Port3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDetailSalesQuotationExterior> SalesOrderDetailSalesQuotationExterior { get; set; }
        public virtual TermsNegotiation TermsNegotiation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesQuotationExteriorDocument> SalesQuotationExteriorDocument { get; set; }
    }
}
