//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCiAuxiliar
    {
        public string CCiAuxiliar { get; set; }
        public string CDsAuxiliar { get; set; }
        public string CTxReferencia { get; set; }
        public string CTxBancos { get; set; }
        public Nullable<bool> BSnFecTipoAuxiliar { get; set; }
        public Nullable<bool> BSnDoc { get; set; }
        public string CCiUsuarioIngr { get; set; }
        public Nullable<System.DateTime> DFiCreacion { get; set; }
        public string CCiUsuarioModi { get; set; }
        public Nullable<System.DateTime> DFuModificacion { get; set; }
        public string CCiUsuarioInac { get; set; }
        public Nullable<System.DateTime> DFuInactiva { get; set; }
        public string CCeAuxiliar { get; set; }
        public string CSNFijaVariable { get; set; }
        public string CCiClaseCosto { get; set; }
    }
}
