//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbsysCatalogState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbsysCatalogState()
        {
            this.RemissionGuide = new HashSet<RemissionGuide>();
            this.RemissionGuideCustomizedAdvancedTransportist = new HashSet<RemissionGuideCustomizedAdvancedTransportist>();
            this.RemissionGuideCustomizedViaticPersonalAssigned = new HashSet<RemissionGuideCustomizedViaticPersonalAssigned>();
            this.RemissionGuideRiver = new HashSet<RemissionGuideRiver>();
            this.RemissionGuideRiverCustomizedAdvancedTransportist = new HashSet<RemissionGuideRiverCustomizedAdvancedTransportist>();
            this.RemissionGuideRiverCustomizedViaticPersonalAssigned = new HashSet<RemissionGuideRiverCustomizedViaticPersonalAssigned>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_TController { get; set; }
        public string codeClasification { get; set; }
        public string codeState { get; set; }
        public string descriptionState { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuide> RemissionGuide { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideCustomizedAdvancedTransportist> RemissionGuideCustomizedAdvancedTransportist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideCustomizedViaticPersonalAssigned> RemissionGuideCustomizedViaticPersonalAssigned { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideRiver> RemissionGuideRiver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideRiverCustomizedAdvancedTransportist> RemissionGuideRiverCustomizedAdvancedTransportist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionGuideRiverCustomizedViaticPersonalAssigned> RemissionGuideRiverCustomizedViaticPersonalAssigned { get; set; }
        public virtual TController TController { get; set; }
    }
}
