//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbsysIntegrationDocumentValidationConfig
    {
        public int id { get; set; }
        public string code { get; set; }
        public int id_IntegrationDocumentConfig { get; set; }
        public int id_ValidateConfig { get; set; }
        public int orderValidate { get; set; }
        public string valueDirectValidate { get; set; }
        public bool isActive { get; set; }
        public int id_userCreate { get; set; }
        public System.DateTime dateCreate { get; set; }
        public int id_userUpdate { get; set; }
        public System.DateTime dateUpdate { get; set; }
    
        public virtual tbsysIntegrationDocumentConfig tbsysIntegrationDocumentConfig { get; set; }
    }
}
