//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRolUser
    {
        public int id { get; set; }
        public int id_userRol { get; set; }
        public int id_User { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserRol UserRol { get; set; }
    }
}
