//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXPANACEASOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vstCiDetMovimiento
    {
        public int NNuControl { get; set; }
        public string CCiCia { get; set; }
        public string CCiDivision { get; set; }
        public string CDsDivision { get; set; }
        public string CCiSucursal { get; set; }
        public string CDsSucursal { get; set; }
        public int NNuRegistro { get; set; }
        public string CCiTipoDato { get; set; }
        public string CCiCuenta { get; set; }
        public string CCiTipoAuxiliar { get; set; }
        public string CCiAuxiliar { get; set; }
        public string CciDpto { get; set; }
        public string CCiProyecto { get; set; }
        public string CCiSubProyecto { get; set; }
        public decimal NNuDebito { get; set; }
        public decimal NNuCredito { get; set; }
        public Nullable<decimal> NNuTercerImporte { get; set; }
        public string CciUnidadMedida { get; set; }
        public string CDsReferencia { get; set; }
        public string CDsReferencia01 { get; set; }
        public string CCiTipoDocCta { get; set; }
        public Nullable<int> NnuNroDocCta { get; set; }
        public Nullable<System.DateTime> DFmFechaDocCta { get; set; }
        public string CCiTipoDocAux { get; set; }
        public Nullable<decimal> NnuNroDocAux { get; set; }
        public Nullable<System.DateTime> DFcAuxiliar { get; set; }
        public Nullable<System.DateTime> DfcFechaVenc { get; set; }
        public string CdsDetalle { get; set; }
        public Nullable<decimal> NNuPrecio { get; set; }
        public string ExisteCuenta { get; set; }
        public string ExisteTipoAuxiliar { get; set; }
        public string ExisteAuxiliar { get; set; }
        public string ExisteDpto { get; set; }
        public string ExisteProyecto { get; set; }
        public string ExisteSubProyecto { get; set; }
        public string ExisteUnidad { get; set; }
        public string CDsCuenta { get; set; }
        public string CCtTituloDetalle { get; set; }
        public string CTxAlias { get; set; }
        public string CdsCuentaEditada { get; set; }
        public string CCiTipoCta { get; set; }
        public string CCeCuenta { get; set; }
        public string BSnAceptaAux { get; set; }
        public string BsnAceptaDpto { get; set; }
        public string BsnAceptaProyecto { get; set; }
        public string BSnTercerImporte { get; set; }
        public string BsnAceptaDoc { get; set; }
        public string BsnAceptaVenc { get; set; }
        public string CDsTipoAuxiliar { get; set; }
        public string CTxCategoria { get; set; }
        public string CCeTipoAuxiliar { get; set; }
        public string CDsAuxiliar { get; set; }
        public string CCeAuxiliar { get; set; }
        public string CDsDpto { get; set; }
        public string CCiTipoPres { get; set; }
        public string CCeDpto { get; set; }
        public string CCeSubProyecto { get; set; }
        public string CDsUnidadMedida { get; set; }
        public string CCiPlanCta { get; set; }
        public short NNuAnio { get; set; }
        public short NNuPeriodo { get; set; }
        public string CCiTipoComprobante { get; set; }
        public int NNuComprobante { get; set; }
        public string CCtEstadoComp { get; set; }
        public System.DateTime DfmFechaContab { get; set; }
        public string CCiUsuarioIngreso { get; set; }
        public Nullable<int> NIdPrPresupuesto { get; set; }
        public string CNuPresupuesto { get; set; }
        public string CDsProyecto { get; set; }
        public string CDsSubProyecto { get; set; }
        public string CSnDptoPresupuesto { get; set; }
    }
}
